/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from './modality';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/render/api';
import * as import3 from '@angular/core/src/linker/element';
import * as import4 from '@angular/core/src/linker/view_utils';
import * as import5 from '@angular/core/src/di/injector';
import * as import6 from '@angular/core/src/linker/view_type';
import * as import7 from '@angular/core/src/change_detection/change_detection';
import * as import8 from 'ionic-angular/navigation/nav-controller';
import * as import9 from 'ionic-angular/components/loading/loading';
import * as import10 from '../../providers/search';
import * as import11 from '../../providers/lens-provider';
import * as import12 from '@angular/core/src/metadata/view';
import * as import13 from '@angular/core/src/linker/component_factory';
import * as import14 from '../../node_modules/ionic-angular/components/toolbar/toolbar.ngfactory';
import * as import15 from '../../node_modules/ionic-angular/components/navbar/navbar.ngfactory';
import * as import16 from '../../node_modules/ionic-angular/components/toolbar/toolbar-title.ngfactory';
import * as import17 from '../../node_modules/ionic-angular/components/content/content.ngfactory';
import * as import18 from '../../node_modules/ionic-angular/components/grid/grid.ngfactory';
import * as import19 from '../../node_modules/ionic-angular/components/button/button.ngfactory';
import * as import20 from 'ionic-angular/config/config';
import * as import21 from '@angular/core/src/linker/element_ref';
import * as import22 from 'ionic-angular/navigation/view-controller';
import * as import23 from 'ionic-angular/components/app/app';
import * as import24 from 'ionic-angular/components/toolbar/toolbar';
import * as import25 from 'ionic-angular/util/keyboard';
import * as import26 from '@angular/core/src/zone/ng_zone';
import * as import27 from 'ionic-angular/components/tabs/tabs';
import * as import28 from 'ionic-angular/components/toolbar/toolbar-title';
import * as import29 from 'ionic-angular/components/navbar/navbar';
import * as import30 from 'ionic-angular/components/grid/grid';
import * as import31 from 'ionic-angular/components/button/button';
import * as import32 from 'ionic-angular/components/content/content';
export class Wrapper_ModalityPage {
  context:import0.ModalityPage;
  changed:boolean;
  constructor(p0:any,p1:any,p2:any,p3:any) {
    this.changed = false;
    this.context = new import0.ModalityPage(p0,p1,p2,p3);
  }
  detectChangesInternal(view:import1.AppView<any>,el:any,throwOnChange:boolean):boolean {
    var changed:any = this.changed;
    this.changed = false;
    return changed;
  }
}
var renderType_ModalityPage_Host:import2.RenderComponentType = (null as any);
class _View_ModalityPage_Host0 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import3.AppElement;
  _ModalityPage_0_4:Wrapper_ModalityPage;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement) {
    super(_View_ModalityPage_Host0,renderType_ModalityPage_Host,import6.ViewType.HOST,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    this._el_0 = this.selectOrCreateHostElement('page-modality',rootSelector,(null as any));
    this._appEl_0 = new import3.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_ModalityPage0(this.viewUtils,this.injector(0),this._appEl_0);
    this._ModalityPage_0_4 = new Wrapper_ModalityPage(this.parentInjector.get(import8.NavController),this.parentInjector.get(import9.LoadingController),this.parentInjector.get(import10.Search),this.parentInjector.get(import11.LensProvider));
    this._appEl_0.initComponent(this._ModalityPage_0_4.context,([] as any[]),compView_0);
    compView_0.create(this._ModalityPage_0_4.context,this.projectableNodes,(null as any));
    this.init(([] as any[]).concat([this._el_0]),[this._el_0],([] as any[]),([] as any[]));
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import0.ModalityPage) && (0 === requestNodeIndex))) { return this._ModalityPage_0_4.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._ModalityPage_0_4.detectChangesInternal(this,this._el_0,throwOnChange);
    this.detectContentChildrenChanges(throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_ModalityPage_Host0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement):import1.AppView<any> {
  if ((renderType_ModalityPage_Host === (null as any))) { (renderType_ModalityPage_Host = viewUtils.createRenderComponentType('',0,import12.ViewEncapsulation.None,([] as any[]),{})); }
  return new _View_ModalityPage_Host0(viewUtils,parentInjector,declarationEl);
}
export const ModalityPageNgFactory:import13.ComponentFactory<import0.ModalityPage> = new import13.ComponentFactory<import0.ModalityPage>('page-modality',viewFactory_ModalityPage_Host0,import0.ModalityPage);
const styles_ModalityPage:any[] = ([] as any[]);
var renderType_ModalityPage:import2.RenderComponentType = (null as any);
class _View_ModalityPage0 extends import1.AppView<import0.ModalityPage> {
  _el_0:any;
  _Header_0_3:import14.Wrapper_Header;
  _text_1:any;
  _el_2:any;
  /*private*/ _appEl_2:import3.AppElement;
  _Navbar_2_4:import15.Wrapper_Navbar;
  _text_3:any;
  _el_4:any;
  /*private*/ _appEl_4:import3.AppElement;
  _ToolbarTitle_4_4:import16.Wrapper_ToolbarTitle;
  _text_5:any;
  _text_6:any;
  _text_7:any;
  _text_8:any;
  _el_9:any;
  /*private*/ _appEl_9:import3.AppElement;
  _Content_9_4:import17.Wrapper_Content;
  _text_10:any;
  _el_11:any;
  _Grid_11_3:import18.Wrapper_Grid;
  _text_12:any;
  _el_13:any;
  _Row_13_3:import18.Wrapper_Row;
  _text_14:any;
  _el_15:any;
  _Col_15_3:import18.Wrapper_Col;
  _text_16:any;
  _el_17:any;
  _text_18:any;
  _text_19:any;
  _text_20:any;
  _text_21:any;
  _el_22:any;
  _Row_22_3:import18.Wrapper_Row;
  _text_23:any;
  _el_24:any;
  _Col_24_3:import18.Wrapper_Col;
  _text_25:any;
  _el_26:any;
  _text_27:any;
  _el_28:any;
  /*private*/ _appEl_28:import3.AppElement;
  _Button_28_4:import19.Wrapper_Button;
  _text_29:any;
  _text_30:any;
  _el_31:any;
  /*private*/ _appEl_31:import3.AppElement;
  _Button_31_4:import19.Wrapper_Button;
  _text_32:any;
  _text_33:any;
  _el_34:any;
  /*private*/ _appEl_34:import3.AppElement;
  _Button_34_4:import19.Wrapper_Button;
  _text_35:any;
  _text_36:any;
  _el_37:any;
  _text_38:any;
  _text_39:any;
  _text_40:any;
  _text_41:any;
  _text_42:any;
  /*private*/ _expr_1:any;
  /*private*/ _expr_2:any;
  /*private*/ _expr_3:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement) {
    super(_View_ModalityPage0,renderType_ModalityPage,import6.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._el_0 = this.renderer.createElement(parentRenderNode,'ion-header',(null as any));
    this._Header_0_3 = new import14.Wrapper_Header(this.parentInjector.get(import20.Config),new import21.ElementRef(this._el_0),this.renderer,this.parentInjector.get(import22.ViewController,(null as any)));
    this._text_1 = this.renderer.createText(this._el_0,'\n  ',(null as any));
    this._el_2 = this.renderer.createElement(this._el_0,'ion-navbar',(null as any));
    this.renderer.setElementAttribute(this._el_2,'class','toolbar');
    this.renderer.setElementAttribute(this._el_2,'color','lens-dark');
    this._appEl_2 = new import3.AppElement(2,0,this,this._el_2);
    var compView_2:any = import15.viewFactory_Navbar0(this.viewUtils,this.injector(2),this._appEl_2);
    this._Navbar_2_4 = new import15.Wrapper_Navbar(this.parentInjector.get(import23.App),this.parentInjector.get(import22.ViewController,(null as any)),this.parentInjector.get(import8.NavController,(null as any)),this.parentInjector.get(import20.Config),new import21.ElementRef(this._el_2),this.renderer);
    this._appEl_2.initComponent(this._Navbar_2_4.context,([] as any[]),compView_2);
    this._text_3 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._el_4 = this.renderer.createElement((null as any),'ion-title',(null as any));
    this.renderer.setElementAttribute(this._el_4,'text-center','');
    this._appEl_4 = new import3.AppElement(4,2,this,this._el_4);
    var compView_4:any = import16.viewFactory_ToolbarTitle0(this.viewUtils,this.injector(4),this._appEl_4);
    this._ToolbarTitle_4_4 = new import16.Wrapper_ToolbarTitle(this.parentInjector.get(import20.Config),new import21.ElementRef(this._el_4),this.renderer,this.parentInjector.get(import24.Toolbar,(null as any)),this._Navbar_2_4.context);
    this._appEl_4.initComponent(this._ToolbarTitle_4_4.context,([] as any[]),compView_4);
    this._text_5 = this.renderer.createText((null as any),'\n      iOptom\n    ',(null as any));
    compView_4.create(this._ToolbarTitle_4_4.context,[([] as any[]).concat([this._text_5])],(null as any));
    this._text_6 = this.renderer.createText((null as any),'\n  ',(null as any));
    compView_2.create(this._Navbar_2_4.context,[
      ([] as any[]),
      ([] as any[]),
      ([] as any[]),
      ([] as any[]).concat([
        this._text_3,
        this._el_4,
        this._text_6
      ]
      )
    ]
    ,(null as any));
    this._text_7 = this.renderer.createText(this._el_0,'\n',(null as any));
    this._text_8 = this.renderer.createText(parentRenderNode,'\n\n',(null as any));
    this._el_9 = this.renderer.createElement(parentRenderNode,'ion-content',(null as any));
    this.renderer.setElementAttribute(this._el_9,'margin-top','');
    this.renderer.setElementAttribute(this._el_9,'padding','');
    this.renderer.setElementAttribute(this._el_9,'text-center','');
    this._appEl_9 = new import3.AppElement(9,(null as any),this,this._el_9);
    var compView_9:any = import17.viewFactory_Content0(this.viewUtils,this.injector(9),this._appEl_9);
    this._Content_9_4 = new import17.Wrapper_Content(this.parentInjector.get(import20.Config),new import21.ElementRef(this._el_9),this.renderer,this.parentInjector.get(import23.App),this.parentInjector.get(import25.Keyboard),this.parentInjector.get(import26.NgZone),this.parentInjector.get(import22.ViewController,(null as any)),this.parentInjector.get(import27.Tabs,(null as any)));
    this._appEl_9.initComponent(this._Content_9_4.context,([] as any[]),compView_9);
    this._text_10 = this.renderer.createText((null as any),'\n  ',(null as any));
    this._el_11 = this.renderer.createElement((null as any),'ion-grid',(null as any));
    this.renderer.setElementAttribute(this._el_11,'style','height: 100%');
    this._Grid_11_3 = new import18.Wrapper_Grid();
    this._text_12 = this.renderer.createText(this._el_11,'\n    ',(null as any));
    this._el_13 = this.renderer.createElement(this._el_11,'ion-row',(null as any));
    this._Row_13_3 = new import18.Wrapper_Row();
    this._text_14 = this.renderer.createText(this._el_13,'\n      ',(null as any));
    this._el_15 = this.renderer.createElement(this._el_13,'ion-col',(null as any));
    this.renderer.setElementAttribute(this._el_15,'offset-10','');
    this.renderer.setElementAttribute(this._el_15,'width-80','');
    this._Col_15_3 = new import18.Wrapper_Col();
    this._text_16 = this.renderer.createText(this._el_15,'\n        ',(null as any));
    this._el_17 = this.renderer.createElement(this._el_15,'h4',(null as any));
    this._text_18 = this.renderer.createText(this._el_17,' Select lens modality ',(null as any));
    this._text_19 = this.renderer.createText(this._el_15,'\n      ',(null as any));
    this._text_20 = this.renderer.createText(this._el_13,'\n    ',(null as any));
    this._text_21 = this.renderer.createText(this._el_11,'\n    ',(null as any));
    this._el_22 = this.renderer.createElement(this._el_11,'ion-row',(null as any));
    this.renderer.setElementAttribute(this._el_22,'center','');
    this.renderer.setElementAttribute(this._el_22,'class','buttons-vertical');
    this._Row_22_3 = new import18.Wrapper_Row();
    this._text_23 = this.renderer.createText(this._el_22,'\n      ',(null as any));
    this._el_24 = this.renderer.createElement(this._el_22,'ion-col',(null as any));
    this.renderer.setElementAttribute(this._el_24,'offset-10','');
    this.renderer.setElementAttribute(this._el_24,'width-80','');
    this._Col_24_3 = new import18.Wrapper_Col();
    this._text_25 = this.renderer.createText(this._el_24,'\n        ',(null as any));
    this._el_26 = this.renderer.createElement(this._el_24,'hr',(null as any));
    this._text_27 = this.renderer.createText(this._el_24,'\n        ',(null as any));
    this._el_28 = this.renderer.createElement(this._el_24,'button',(null as any));
    this.renderer.setElementAttribute(this._el_28,'block','');
    this.renderer.setElementAttribute(this._el_28,'color','lens-dark');
    this.renderer.setElementAttribute(this._el_28,'ion-button','');
    this._appEl_28 = new import3.AppElement(28,24,this,this._el_28);
    var compView_28:any = import19.viewFactory_Button0(this.viewUtils,this.injector(28),this._appEl_28);
    this._Button_28_4 = new import19.Wrapper_Button((null as any),'',this.parentInjector.get(import20.Config),new import21.ElementRef(this._el_28),this.renderer);
    this._appEl_28.initComponent(this._Button_28_4.context,([] as any[]),compView_28);
    this._text_29 = this.renderer.createText((null as any),'Daily',(null as any));
    compView_28.create(this._Button_28_4.context,[([] as any[]).concat([this._text_29])],(null as any));
    this._text_30 = this.renderer.createText(this._el_24,'\n        ',(null as any));
    this._el_31 = this.renderer.createElement(this._el_24,'button',(null as any));
    this.renderer.setElementAttribute(this._el_31,'block','');
    this.renderer.setElementAttribute(this._el_31,'color','lens-dark');
    this.renderer.setElementAttribute(this._el_31,'ion-button','');
    this._appEl_31 = new import3.AppElement(31,24,this,this._el_31);
    var compView_31:any = import19.viewFactory_Button0(this.viewUtils,this.injector(31),this._appEl_31);
    this._Button_31_4 = new import19.Wrapper_Button((null as any),'',this.parentInjector.get(import20.Config),new import21.ElementRef(this._el_31),this.renderer);
    this._appEl_31.initComponent(this._Button_31_4.context,([] as any[]),compView_31);
    this._text_32 = this.renderer.createText((null as any),'Fornighty',(null as any));
    compView_31.create(this._Button_31_4.context,[([] as any[]).concat([this._text_32])],(null as any));
    this._text_33 = this.renderer.createText(this._el_24,'\n        ',(null as any));
    this._el_34 = this.renderer.createElement(this._el_24,'button',(null as any));
    this.renderer.setElementAttribute(this._el_34,'block','');
    this.renderer.setElementAttribute(this._el_34,'color','lens-dark');
    this.renderer.setElementAttribute(this._el_34,'ion-button','');
    this._appEl_34 = new import3.AppElement(34,24,this,this._el_34);
    var compView_34:any = import19.viewFactory_Button0(this.viewUtils,this.injector(34),this._appEl_34);
    this._Button_34_4 = new import19.Wrapper_Button((null as any),'',this.parentInjector.get(import20.Config),new import21.ElementRef(this._el_34),this.renderer);
    this._appEl_34.initComponent(this._Button_34_4.context,([] as any[]),compView_34);
    this._text_35 = this.renderer.createText((null as any),'Monthly',(null as any));
    compView_34.create(this._Button_34_4.context,[([] as any[]).concat([this._text_35])],(null as any));
    this._text_36 = this.renderer.createText(this._el_24,'\n        ',(null as any));
    this._el_37 = this.renderer.createElement(this._el_24,'hr',(null as any));
    this._text_38 = this.renderer.createText(this._el_24,'\n      ',(null as any));
    this._text_39 = this.renderer.createText(this._el_22,'\n    ',(null as any));
    this._text_40 = this.renderer.createText(this._el_11,'\n  ',(null as any));
    this._text_41 = this.renderer.createText((null as any),'\n',(null as any));
    compView_9.create(this._Content_9_4.context,[
      ([] as any[]),
      ([] as any[]).concat([
        this._text_10,
        this._el_11,
        this._text_41
      ]
      ),
      ([] as any[])
    ]
    ,(null as any));
    this._text_42 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this._expr_1 = import7.UNINITIALIZED;
    this._expr_2 = import7.UNINITIALIZED;
    this._expr_3 = import7.UNINITIALIZED;
    var disposable_0:Function = this.renderer.listen(this._el_28,'click',this.eventHandler(this._handle_click_28_0.bind(this)));
    this.init(([] as any[]),[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._text_6,
      this._text_7,
      this._text_8,
      this._el_9,
      this._text_10,
      this._el_11,
      this._text_12,
      this._el_13,
      this._text_14,
      this._el_15,
      this._text_16,
      this._el_17,
      this._text_18,
      this._text_19,
      this._text_20,
      this._text_21,
      this._el_22,
      this._text_23,
      this._el_24,
      this._text_25,
      this._el_26,
      this._text_27,
      this._el_28,
      this._text_29,
      this._text_30,
      this._el_31,
      this._text_32,
      this._text_33,
      this._el_34,
      this._text_35,
      this._text_36,
      this._el_37,
      this._text_38,
      this._text_39,
      this._text_40,
      this._text_41,
      this._text_42
    ]
    ,[disposable_0],([] as any[]));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import28.ToolbarTitle) && ((4 <= requestNodeIndex) && (requestNodeIndex <= 5)))) { return this._ToolbarTitle_4_4.context; }
    if (((token === import29.Navbar) && ((2 <= requestNodeIndex) && (requestNodeIndex <= 6)))) { return this._Navbar_2_4.context; }
    if (((token === import24.Header) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 7)))) { return this._Header_0_3.context; }
    if (((token === import30.Col) && ((15 <= requestNodeIndex) && (requestNodeIndex <= 19)))) { return this._Col_15_3.context; }
    if (((token === import30.Row) && ((13 <= requestNodeIndex) && (requestNodeIndex <= 20)))) { return this._Row_13_3.context; }
    if (((token === import31.Button) && ((28 <= requestNodeIndex) && (requestNodeIndex <= 29)))) { return this._Button_28_4.context; }
    if (((token === import31.Button) && ((31 <= requestNodeIndex) && (requestNodeIndex <= 32)))) { return this._Button_31_4.context; }
    if (((token === import31.Button) && ((34 <= requestNodeIndex) && (requestNodeIndex <= 35)))) { return this._Button_34_4.context; }
    if (((token === import30.Col) && ((24 <= requestNodeIndex) && (requestNodeIndex <= 38)))) { return this._Col_24_3.context; }
    if (((token === import30.Row) && ((22 <= requestNodeIndex) && (requestNodeIndex <= 39)))) { return this._Row_22_3.context; }
    if (((token === import30.Grid) && ((11 <= requestNodeIndex) && (requestNodeIndex <= 40)))) { return this._Grid_11_3.context; }
    if (((token === import32.Content) && ((9 <= requestNodeIndex) && (requestNodeIndex <= 41)))) { return this._Content_9_4.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._Header_0_3.detectChangesInternal(this,this._el_0,throwOnChange);
    const currVal_0:any = 'lens-dark';
    this._Navbar_2_4.check_color(currVal_0,throwOnChange,false);
    this._Navbar_2_4.detectChangesInternal(this,this._el_2,throwOnChange);
    if (this._ToolbarTitle_4_4.detectChangesInternal(this,this._el_4,throwOnChange)) { this._appEl_4.componentView.markAsCheckOnce(); }
    if (this._Content_9_4.detectChangesInternal(this,this._el_9,throwOnChange)) { this._appEl_9.componentView.markAsCheckOnce(); }
    this._Grid_11_3.detectChangesInternal(this,this._el_11,throwOnChange);
    this._Row_13_3.detectChangesInternal(this,this._el_13,throwOnChange);
    this._Col_15_3.detectChangesInternal(this,this._el_15,throwOnChange);
    this._Row_22_3.detectChangesInternal(this,this._el_22,throwOnChange);
    this._Col_24_3.detectChangesInternal(this,this._el_24,throwOnChange);
    const currVal_5:any = '';
    this._Button_28_4.check_block(currVal_5,throwOnChange,false);
    const currVal_6:any = 'lens-dark';
    this._Button_28_4.check_color(currVal_6,throwOnChange,false);
    if (this._Button_28_4.detectChangesInternal(this,this._el_28,throwOnChange)) { this._appEl_28.componentView.markAsCheckOnce(); }
    const currVal_7:any = '';
    this._Button_31_4.check_block(currVal_7,throwOnChange,false);
    const currVal_8:any = 'lens-dark';
    this._Button_31_4.check_color(currVal_8,throwOnChange,false);
    if (this._Button_31_4.detectChangesInternal(this,this._el_31,throwOnChange)) { this._appEl_31.componentView.markAsCheckOnce(); }
    const currVal_9:any = '';
    this._Button_34_4.check_block(currVal_9,throwOnChange,false);
    const currVal_10:any = 'lens-dark';
    this._Button_34_4.check_color(currVal_10,throwOnChange,false);
    if (this._Button_34_4.detectChangesInternal(this,this._el_34,throwOnChange)) { this._appEl_34.componentView.markAsCheckOnce(); }
    this.detectContentChildrenChanges(throwOnChange);
    if (!throwOnChange) {
      if ((this.numberOfChecks === 0)) { this._Button_28_4.context.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Button_31_4.context.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Button_34_4.context.ngAfterContentInit(); }
    }
    const currVal_1:any = this._Navbar_2_4.context._hidden;
    if (import4.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this.renderer.setElementProperty(this._el_2,'hidden',currVal_1);
      this._expr_1 = currVal_1;
    }
    const currVal_2:any = this._Navbar_2_4.context._sbPadding;
    if (import4.checkBinding(throwOnChange,this._expr_2,currVal_2)) {
      this.renderer.setElementClass(this._el_2,'statusbar-padding',currVal_2);
      this._expr_2 = currVal_2;
    }
    const currVal_3:any = this._Content_9_4.context._sbPadding;
    if (import4.checkBinding(throwOnChange,this._expr_3,currVal_3)) {
      this.renderer.setElementClass(this._el_9,'statusbar-padding',currVal_3);
      this._expr_3 = currVal_3;
    }
    this.detectViewChildrenChanges(throwOnChange);
    if (!throwOnChange) { if ((this.numberOfChecks === 0)) { this._Navbar_2_4.context.ngAfterViewInit(); } }
  }
  destroyInternal():void {
    this._Content_9_4.context.ngOnDestroy();
  }
  private _handle_click_28_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.daily()) !== false);
    return (true && pd_0);
  }
}
export function viewFactory_ModalityPage0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement):import1.AppView<import0.ModalityPage> {
  if ((renderType_ModalityPage === (null as any))) { (renderType_ModalityPage = viewUtils.createRenderComponentType('',0,import12.ViewEncapsulation.None,styles_ModalityPage,{})); }
  return new _View_ModalityPage0(viewUtils,parentInjector,declarationEl);
}