/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from './sphere';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/render/api';
import * as import3 from '@angular/core/src/linker/element';
import * as import4 from '@angular/core/src/linker/view_utils';
import * as import5 from '@angular/core/src/di/injector';
import * as import6 from '@angular/core/src/linker/view_type';
import * as import7 from '@angular/core/src/change_detection/change_detection';
import * as import8 from 'ionic-angular/navigation/nav-controller';
import * as import9 from '../../providers/lens';
import * as import10 from '@angular/core/src/metadata/view';
import * as import11 from '@angular/core/src/linker/component_factory';
import * as import12 from '../../node_modules/ionic-angular/components/toolbar/toolbar.ngfactory';
import * as import13 from '../../node_modules/ionic-angular/components/navbar/navbar.ngfactory';
import * as import14 from '../../node_modules/ionic-angular/components/toolbar/toolbar-title.ngfactory';
import * as import15 from '../../node_modules/ionic-angular/components/content/content.ngfactory';
import * as import16 from '../../node_modules/ionic-angular/components/grid/grid.ngfactory';
import * as import17 from '../../node_modules/ionic-angular/components/button/button.ngfactory';
import * as import18 from '../../node_modules/ionic-angular/components/icon/icon.ngfactory';
import * as import19 from '../../node_modules/@angular/forms/src/directives/ng_model.ngfactory';
import * as import20 from '../../node_modules/@angular/forms/src/directives/ng_control_status.ngfactory';
import * as import21 from '../../node_modules/ionic-angular/components/input/input.ngfactory';
import * as import22 from '../../node_modules/ionic-angular/components/item/item.ngfactory';
import * as import23 from '@angular/core/src/linker/query_list';
import * as import24 from '../../node_modules/ionic-angular/components/label/label.ngfactory';
import * as import25 from '../../node_modules/ionic-angular/components/toggle/toggle.ngfactory';
import * as import26 from '../../node_modules/@angular/common/src/directives/ng_if.ngfactory';
import * as import27 from 'ionic-angular/config/config';
import * as import28 from '@angular/core/src/linker/element_ref';
import * as import29 from 'ionic-angular/navigation/view-controller';
import * as import30 from 'ionic-angular/components/app/app';
import * as import31 from 'ionic-angular/components/toolbar/toolbar';
import * as import32 from 'ionic-angular/util/keyboard';
import * as import33 from '@angular/core/src/zone/ng_zone';
import * as import34 from 'ionic-angular/components/tabs/tabs';
import * as import35 from 'ionic-angular/util/form';
import * as import36 from 'ionic-angular/components/item/item';
import * as import37 from 'ionic-angular/platform/platform';
import * as import38 from 'ionic-angular/components/item/item-reorder';
import * as import39 from 'ionic-angular/util/haptic';
import * as import40 from '@angular/core/src/linker/template_ref';
import * as import41 from 'ionic-angular/components/toolbar/toolbar-title';
import * as import42 from 'ionic-angular/components/navbar/navbar';
import * as import43 from 'ionic-angular/components/icon/icon';
import * as import44 from 'ionic-angular/components/button/button';
import * as import45 from 'ionic-angular/components/grid/grid';
import * as import46 from '@angular/forms/src/directives/ng_model';
import * as import47 from '@angular/forms/src/directives/ng_control';
import * as import48 from '@angular/forms/src/directives/ng_control_status';
import * as import49 from 'ionic-angular/components/input/input';
import * as import50 from 'ionic-angular/components/label/label';
import * as import51 from 'ionic-angular/components/toggle/toggle';
import * as import52 from '@angular/forms/src/directives/control_value_accessor';
import * as import53 from '@angular/common/src/directives/ng_if';
import * as import54 from 'ionic-angular/components/content/content';
export class Wrapper_SpherePage {
  context:import0.SpherePage;
  changed:boolean;
  constructor(p0:any,p1:any) {
    this.changed = false;
    this.context = new import0.SpherePage(p0,p1);
  }
  detectChangesInternal(view:import1.AppView<any>,el:any,throwOnChange:boolean):boolean {
    var changed:any = this.changed;
    this.changed = false;
    return changed;
  }
}
var renderType_SpherePage_Host:import2.RenderComponentType = (null as any);
class _View_SpherePage_Host0 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import3.AppElement;
  _SpherePage_0_4:Wrapper_SpherePage;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement) {
    super(_View_SpherePage_Host0,renderType_SpherePage_Host,import6.ViewType.HOST,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    this._el_0 = this.selectOrCreateHostElement('page-sphere',rootSelector,(null as any));
    this._appEl_0 = new import3.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_SpherePage0(this.viewUtils,this.injector(0),this._appEl_0);
    this._SpherePage_0_4 = new Wrapper_SpherePage(this.parentInjector.get(import8.NavController),this.parentInjector.get(import9.LensProvider));
    this._appEl_0.initComponent(this._SpherePage_0_4.context,([] as any[]),compView_0);
    compView_0.create(this._SpherePage_0_4.context,this.projectableNodes,(null as any));
    this.init(([] as any[]).concat([this._el_0]),[this._el_0],([] as any[]),([] as any[]));
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import0.SpherePage) && (0 === requestNodeIndex))) { return this._SpherePage_0_4.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._SpherePage_0_4.detectChangesInternal(this,this._el_0,throwOnChange);
    this.detectContentChildrenChanges(throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_SpherePage_Host0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement):import1.AppView<any> {
  if ((renderType_SpherePage_Host === (null as any))) { (renderType_SpherePage_Host = viewUtils.createRenderComponentType('',0,import10.ViewEncapsulation.None,([] as any[]),{})); }
  return new _View_SpherePage_Host0(viewUtils,parentInjector,declarationEl);
}
export const SpherePageNgFactory:import11.ComponentFactory<import0.SpherePage> = new import11.ComponentFactory<import0.SpherePage>('page-sphere',viewFactory_SpherePage_Host0,import0.SpherePage);
const styles_SpherePage:any[] = ([] as any[]);
var renderType_SpherePage:import2.RenderComponentType = (null as any);
class _View_SpherePage0 extends import1.AppView<import0.SpherePage> {
  _el_0:any;
  _Header_0_3:import12.Wrapper_Header;
  _text_1:any;
  _el_2:any;
  /*private*/ _appEl_2:import3.AppElement;
  _Navbar_2_4:import13.Wrapper_Navbar;
  _text_3:any;
  _el_4:any;
  /*private*/ _appEl_4:import3.AppElement;
  _ToolbarTitle_4_4:import14.Wrapper_ToolbarTitle;
  _text_5:any;
  _text_6:any;
  _text_7:any;
  _text_8:any;
  _el_9:any;
  /*private*/ _appEl_9:import3.AppElement;
  _Content_9_4:import15.Wrapper_Content;
  _text_10:any;
  _el_11:any;
  _Grid_11_3:import16.Wrapper_Grid;
  _text_12:any;
  _el_13:any;
  _Row_13_3:import16.Wrapper_Row;
  _text_14:any;
  _el_15:any;
  _Col_15_3:import16.Wrapper_Col;
  _text_16:any;
  _el_17:any;
  _text_18:any;
  _text_19:any;
  _el_20:any;
  _text_21:any;
  _el_22:any;
  _Row_22_3:import16.Wrapper_Row;
  _text_23:any;
  _el_24:any;
  _Col_24_3:import16.Wrapper_Col;
  _text_25:any;
  _el_26:any;
  /*private*/ _appEl_26:import3.AppElement;
  _Button_26_4:import17.Wrapper_Button;
  _text_27:any;
  _el_28:any;
  _Icon_28_3:import18.Wrapper_Icon;
  _text_29:any;
  _text_30:any;
  _text_31:any;
  _el_32:any;
  _Col_32_3:import16.Wrapper_Col;
  _text_33:any;
  _el_34:any;
  /*private*/ _appEl_34:import3.AppElement;
  _NgModel_34_4:import19.Wrapper_NgModel;
  _NgControl_34_5:any;
  _NgControlStatus_34_6:import20.Wrapper_NgControlStatus;
  _TextInput_34_7:import21.Wrapper_TextInput;
  _text_35:any;
  _text_36:any;
  _el_37:any;
  _Col_37_3:import16.Wrapper_Col;
  _text_38:any;
  _el_39:any;
  /*private*/ _appEl_39:import3.AppElement;
  _Button_39_4:import17.Wrapper_Button;
  _text_40:any;
  _el_41:any;
  _Icon_41_3:import18.Wrapper_Icon;
  _text_42:any;
  _text_43:any;
  _text_44:any;
  _text_45:any;
  _el_46:any;
  _Row_46_3:import16.Wrapper_Row;
  _text_47:any;
  _el_48:any;
  _Col_48_3:import16.Wrapper_Col;
  _text_49:any;
  _el_50:any;
  /*private*/ _appEl_50:import3.AppElement;
  _Item_50_4:import22.Wrapper_Item;
  _ItemContent_50_5:import22.Wrapper_ItemContent;
  _query_Label_50_0:import23.QueryList<any>;
  _query_Button_50_1:import23.QueryList<any>;
  _query_Icon_50_2:import23.QueryList<any>;
  _text_51:any;
  _el_52:any;
  _Label_52_3:import24.Wrapper_Label;
  _text_53:any;
  _text_54:any;
  _el_55:any;
  /*private*/ _appEl_55:import3.AppElement;
  _Toggle_55_4:import25.Wrapper_Toggle;
  _NG_VALUE_ACCESSOR_55_5:any[];
  _NgModel_55_6:import19.Wrapper_NgModel;
  _NgControl_55_7:any;
  _NgControlStatus_55_8:import20.Wrapper_NgControlStatus;
  _text_56:any;
  _text_57:any;
  _text_58:any;
  _text_59:any;
  _anchor_60:any;
  /*private*/ _appEl_60:import3.AppElement;
  _TemplateRef_60_5:any;
  _NgIf_60_6:import26.Wrapper_NgIf;
  _text_61:any;
  _text_62:any;
  _text_63:any;
  _el_64:any;
  _Footer_64_3:import12.Wrapper_Footer;
  _text_65:any;
  _el_66:any;
  _Row_66_3:import16.Wrapper_Row;
  _text_67:any;
  _el_68:any;
  _Col_68_3:import16.Wrapper_Col;
  _text_69:any;
  _el_70:any;
  /*private*/ _appEl_70:import3.AppElement;
  _Button_70_4:import17.Wrapper_Button;
  _text_71:any;
  _text_72:any;
  _el_73:any;
  _text_74:any;
  _text_75:any;
  _text_76:any;
  _text_77:any;
  _text_78:any;
  /*private*/ _expr_1:any;
  /*private*/ _expr_2:any;
  /*private*/ _expr_3:any;
  /*private*/ _expr_8:any;
  /*private*/ _expr_11:any;
  /*private*/ _expr_12:any;
  /*private*/ _expr_13:any;
  /*private*/ _expr_14:any;
  /*private*/ _expr_15:any;
  /*private*/ _expr_16:any;
  /*private*/ _expr_22:any;
  /*private*/ _expr_25:any;
  /*private*/ _expr_27:any;
  /*private*/ _expr_28:any;
  /*private*/ _expr_29:any;
  /*private*/ _expr_30:any;
  /*private*/ _expr_31:any;
  /*private*/ _expr_32:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement) {
    super(_View_SpherePage0,renderType_SpherePage,import6.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._el_0 = this.renderer.createElement(parentRenderNode,'ion-header',(null as any));
    this._Header_0_3 = new import12.Wrapper_Header(this.parentInjector.get(import27.Config),new import28.ElementRef(this._el_0),this.renderer,this.parentInjector.get(import29.ViewController,(null as any)));
    this._text_1 = this.renderer.createText(this._el_0,'\n  ',(null as any));
    this._el_2 = this.renderer.createElement(this._el_0,'ion-navbar',(null as any));
    this.renderer.setElementAttribute(this._el_2,'class','toolbar');
    this.renderer.setElementAttribute(this._el_2,'color','lens-dark');
    this._appEl_2 = new import3.AppElement(2,0,this,this._el_2);
    var compView_2:any = import13.viewFactory_Navbar0(this.viewUtils,this.injector(2),this._appEl_2);
    this._Navbar_2_4 = new import13.Wrapper_Navbar(this.parentInjector.get(import30.App),this.parentInjector.get(import29.ViewController,(null as any)),this.parentInjector.get(import8.NavController,(null as any)),this.parentInjector.get(import27.Config),new import28.ElementRef(this._el_2),this.renderer);
    this._appEl_2.initComponent(this._Navbar_2_4.context,([] as any[]),compView_2);
    this._text_3 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._el_4 = this.renderer.createElement((null as any),'ion-title',(null as any));
    this.renderer.setElementAttribute(this._el_4,'text-center','');
    this._appEl_4 = new import3.AppElement(4,2,this,this._el_4);
    var compView_4:any = import14.viewFactory_ToolbarTitle0(this.viewUtils,this.injector(4),this._appEl_4);
    this._ToolbarTitle_4_4 = new import14.Wrapper_ToolbarTitle(this.parentInjector.get(import27.Config),new import28.ElementRef(this._el_4),this.renderer,this.parentInjector.get(import31.Toolbar,(null as any)),this._Navbar_2_4.context);
    this._appEl_4.initComponent(this._ToolbarTitle_4_4.context,([] as any[]),compView_4);
    this._text_5 = this.renderer.createText((null as any),'\n      iOptom\n    ',(null as any));
    compView_4.create(this._ToolbarTitle_4_4.context,[([] as any[]).concat([this._text_5])],(null as any));
    this._text_6 = this.renderer.createText((null as any),'\n  ',(null as any));
    compView_2.create(this._Navbar_2_4.context,[
      ([] as any[]),
      ([] as any[]),
      ([] as any[]),
      ([] as any[]).concat([
        this._text_3,
        this._el_4,
        this._text_6
      ]
      )
    ]
    ,(null as any));
    this._text_7 = this.renderer.createText(this._el_0,'\n',(null as any));
    this._text_8 = this.renderer.createText(parentRenderNode,'\n\n\n',(null as any));
    this._el_9 = this.renderer.createElement(parentRenderNode,'ion-content',(null as any));
    this.renderer.setElementAttribute(this._el_9,'margin-top','');
    this.renderer.setElementAttribute(this._el_9,'padding','');
    this.renderer.setElementAttribute(this._el_9,'text-center','');
    this._appEl_9 = new import3.AppElement(9,(null as any),this,this._el_9);
    var compView_9:any = import15.viewFactory_Content0(this.viewUtils,this.injector(9),this._appEl_9);
    this._Content_9_4 = new import15.Wrapper_Content(this.parentInjector.get(import27.Config),new import28.ElementRef(this._el_9),this.renderer,this.parentInjector.get(import30.App),this.parentInjector.get(import32.Keyboard),this.parentInjector.get(import33.NgZone),this.parentInjector.get(import29.ViewController,(null as any)),this.parentInjector.get(import34.Tabs,(null as any)));
    this._appEl_9.initComponent(this._Content_9_4.context,([] as any[]),compView_9);
    this._text_10 = this.renderer.createText((null as any),'\n\n  ',(null as any));
    this._el_11 = this.renderer.createElement((null as any),'ion-grid',(null as any));
    this.renderer.setElementAttribute(this._el_11,'style','height: 100%');
    this._Grid_11_3 = new import16.Wrapper_Grid();
    this._text_12 = this.renderer.createText(this._el_11,'\n    ',(null as any));
    this._el_13 = this.renderer.createElement(this._el_11,'ion-row',(null as any));
    this._Row_13_3 = new import16.Wrapper_Row();
    this._text_14 = this.renderer.createText(this._el_13,'\n      ',(null as any));
    this._el_15 = this.renderer.createElement(this._el_13,'ion-col',(null as any));
    this._Col_15_3 = new import16.Wrapper_Col();
    this._text_16 = this.renderer.createText(this._el_15,'\n        ',(null as any));
    this._el_17 = this.renderer.createElement(this._el_15,'h4',(null as any));
    this.renderer.setElementAttribute(this._el_17,'style','margin-bottom: 1.6em');
    this._text_18 = this.renderer.createText(this._el_17,' Enter Spectacle Prescription ',(null as any));
    this._text_19 = this.renderer.createText(this._el_15,'\n        ',(null as any));
    this._el_20 = this.renderer.createElement(this._el_15,'hr',(null as any));
    this.renderer.setElementAttribute(this._el_20,'style','margin-bottom: 2.6em');
    this._text_21 = this.renderer.createText(this._el_15,'\n        ',(null as any));
    this._el_22 = this.renderer.createElement(this._el_15,'ion-row',(null as any));
    this._Row_22_3 = new import16.Wrapper_Row();
    this._text_23 = this.renderer.createText(this._el_22,'\n          ',(null as any));
    this._el_24 = this.renderer.createElement(this._el_22,'ion-col',(null as any));
    this.renderer.setElementAttribute(this._el_24,'center','');
    this.renderer.setElementAttribute(this._el_24,'text-right','');
    this.renderer.setElementAttribute(this._el_24,'width-25','');
    this._Col_24_3 = new import16.Wrapper_Col();
    this._text_25 = this.renderer.createText(this._el_24,'\n            ',(null as any));
    this._el_26 = this.renderer.createElement(this._el_24,'button',(null as any));
    this.renderer.setElementAttribute(this._el_26,'clear','');
    this.renderer.setElementAttribute(this._el_26,'color','lens-light');
    this.renderer.setElementAttribute(this._el_26,'ion-button','');
    this._appEl_26 = new import3.AppElement(26,24,this,this._el_26);
    var compView_26:any = import17.viewFactory_Button0(this.viewUtils,this.injector(26),this._appEl_26);
    this._Button_26_4 = new import17.Wrapper_Button((null as any),'',this.parentInjector.get(import27.Config),new import28.ElementRef(this._el_26),this.renderer);
    this._appEl_26.initComponent(this._Button_26_4.context,([] as any[]),compView_26);
    this._text_27 = this.renderer.createText((null as any),'\n              ',(null as any));
    this._el_28 = this.renderer.createElement((null as any),'ion-icon',(null as any));
    this.renderer.setElementAttribute(this._el_28,'name','remove');
    this.renderer.setElementAttribute(this._el_28,'role','img');
    this._Icon_28_3 = new import18.Wrapper_Icon(this.parentInjector.get(import27.Config),new import28.ElementRef(this._el_28),this.renderer);
    this._text_29 = this.renderer.createText((null as any),'\n            ',(null as any));
      compView_26.create(this._Button_26_4.context,[([] as any[]).concat([
        this._text_27,
        this._el_28,
        this._text_29
      ]
    )],(null as any));
    this._text_30 = this.renderer.createText(this._el_24,'\n          ',(null as any));
    this._text_31 = this.renderer.createText(this._el_22,'\n          ',(null as any));
    this._el_32 = this.renderer.createElement(this._el_22,'ion-col',(null as any));
    this.renderer.setElementAttribute(this._el_32,'center','');
    this.renderer.setElementAttribute(this._el_32,'style','font-size: 2em');
    this.renderer.setElementAttribute(this._el_32,'width-50','');
    this._Col_32_3 = new import16.Wrapper_Col();
    this._text_33 = this.renderer.createText(this._el_32,'\n            ',(null as any));
    this._el_34 = this.renderer.createElement(this._el_32,'ion-input',(null as any));
    this.renderer.setElementAttribute(this._el_34,'text-center','');
    this.renderer.setElementAttribute(this._el_34,'type','number');
    this._appEl_34 = new import3.AppElement(34,32,this,this._el_34);
    var compView_34:any = import21.viewFactory_TextInput0(this.viewUtils,this.injector(34),this._appEl_34);
    this._NgModel_34_4 = new import19.Wrapper_NgModel((null as any),(null as any),(null as any),(null as any));
    this._NgControl_34_5 = this._NgModel_34_4.context;
    this._NgControlStatus_34_6 = new import20.Wrapper_NgControlStatus(this._NgControl_34_5);
    this._TextInput_34_7 = new import21.Wrapper_TextInput(this.parentInjector.get(import27.Config),this.parentInjector.get(import35.Form),this.parentInjector.get(import36.Item,(null as any)),this.parentInjector.get(import30.App),this.parentInjector.get(import37.Platform),new import28.ElementRef(this._el_34),this.renderer,this._Content_9_4.context,this.parentInjector.get(import8.NavController,(null as any)),this._NgControl_34_5);
    this._appEl_34.initComponent(this._TextInput_34_7.context,([] as any[]),compView_34);
    compView_34.create(this._TextInput_34_7.context,([] as any[]),(null as any));
    this._text_35 = this.renderer.createText(this._el_32,'\n          ',(null as any));
    this._text_36 = this.renderer.createText(this._el_22,'\n          ',(null as any));
    this._el_37 = this.renderer.createElement(this._el_22,'ion-col',(null as any));
    this.renderer.setElementAttribute(this._el_37,'center','');
    this.renderer.setElementAttribute(this._el_37,'text-left','');
    this.renderer.setElementAttribute(this._el_37,'width-25','');
    this._Col_37_3 = new import16.Wrapper_Col();
    this._text_38 = this.renderer.createText(this._el_37,'\n            ',(null as any));
    this._el_39 = this.renderer.createElement(this._el_37,'button',(null as any));
    this.renderer.setElementAttribute(this._el_39,'clear','');
    this.renderer.setElementAttribute(this._el_39,'color','lens-light');
    this.renderer.setElementAttribute(this._el_39,'ion-button','');
    this._appEl_39 = new import3.AppElement(39,37,this,this._el_39);
    var compView_39:any = import17.viewFactory_Button0(this.viewUtils,this.injector(39),this._appEl_39);
    this._Button_39_4 = new import17.Wrapper_Button((null as any),'',this.parentInjector.get(import27.Config),new import28.ElementRef(this._el_39),this.renderer);
    this._appEl_39.initComponent(this._Button_39_4.context,([] as any[]),compView_39);
    this._text_40 = this.renderer.createText((null as any),'\n              ',(null as any));
    this._el_41 = this.renderer.createElement((null as any),'ion-icon',(null as any));
    this.renderer.setElementAttribute(this._el_41,'name','add');
    this.renderer.setElementAttribute(this._el_41,'role','img');
    this._Icon_41_3 = new import18.Wrapper_Icon(this.parentInjector.get(import27.Config),new import28.ElementRef(this._el_41),this.renderer);
    this._text_42 = this.renderer.createText((null as any),'\n            ',(null as any));
      compView_39.create(this._Button_39_4.context,[([] as any[]).concat([
        this._text_40,
        this._el_41,
        this._text_42
      ]
    )],(null as any));
    this._text_43 = this.renderer.createText(this._el_37,'\n          ',(null as any));
    this._text_44 = this.renderer.createText(this._el_22,'\n        ',(null as any));
    this._text_45 = this.renderer.createText(this._el_15,'\n        ',(null as any));
    this._el_46 = this.renderer.createElement(this._el_15,'ion-row',(null as any));
    this._Row_46_3 = new import16.Wrapper_Row();
    this._text_47 = this.renderer.createText(this._el_46,'\n          ',(null as any));
    this._el_48 = this.renderer.createElement(this._el_46,'ion-col',(null as any));
    this._Col_48_3 = new import16.Wrapper_Col();
    this._text_49 = this.renderer.createText(this._el_48,'\n            ',(null as any));
    this._el_50 = this.renderer.createElement(this._el_48,'ion-item',(null as any));
    this.renderer.setElementAttribute(this._el_50,'class','item item-block');
    this.renderer.setElementAttribute(this._el_50,'no-lines','');
    this._appEl_50 = new import3.AppElement(50,48,this,this._el_50);
    var compView_50:any = import22.viewFactory_Item0(this.viewUtils,this.injector(50),this._appEl_50);
    this._Item_50_4 = new import22.Wrapper_Item(this.parentInjector.get(import35.Form),this.parentInjector.get(import27.Config),new import28.ElementRef(this._el_50),this.renderer,this.parentInjector.get(import38.ItemReorder,(null as any)));
    this._ItemContent_50_5 = new import22.Wrapper_ItemContent();
    this._query_Label_50_0 = new import23.QueryList<any>();
    this._query_Button_50_1 = new import23.QueryList<any>();
    this._query_Icon_50_2 = new import23.QueryList<any>();
    this._appEl_50.initComponent(this._Item_50_4.context,([] as any[]),compView_50);
    this._text_51 = this.renderer.createText((null as any),'\n              ',(null as any));
    this._el_52 = this.renderer.createElement((null as any),'ion-label',(null as any));
    this._Label_52_3 = new import24.Wrapper_Label(this.parentInjector.get(import27.Config),new import28.ElementRef(this._el_52),this.renderer,(null as any),(null as any),(null as any),(null as any));
    this._text_53 = this.renderer.createText(this._el_52,'Has astigmatism',(null as any));
    this._text_54 = this.renderer.createText((null as any),'\n              ',(null as any));
    this._el_55 = this.renderer.createElement((null as any),'ion-toggle',(null as any));
    this.renderer.setElementAttribute(this._el_55,'color','lens-light');
    this._appEl_55 = new import3.AppElement(55,50,this,this._el_55);
    var compView_55:any = import25.viewFactory_Toggle0(this.viewUtils,this.injector(55),this._appEl_55);
    this._Toggle_55_4 = new import25.Wrapper_Toggle(this.parentInjector.get(import35.Form),this.parentInjector.get(import27.Config),new import28.ElementRef(this._el_55),this.renderer,this.parentInjector.get(import39.Haptic),this._Item_50_4.context);
    this._NG_VALUE_ACCESSOR_55_5 = [this._Toggle_55_4.context];
    this._NgModel_55_6 = new import19.Wrapper_NgModel((null as any),(null as any),(null as any),this._NG_VALUE_ACCESSOR_55_5);
    this._NgControl_55_7 = this._NgModel_55_6.context;
    this._NgControlStatus_55_8 = new import20.Wrapper_NgControlStatus(this._NgControl_55_7);
    this._appEl_55.initComponent(this._Toggle_55_4.context,([] as any[]),compView_55);
    compView_55.create(this._Toggle_55_4.context,([] as any[]),(null as any));
    this._text_56 = this.renderer.createText((null as any),'\n            ',(null as any));
    this._query_Label_50_0.reset([this._Label_52_3.context]);
    this._Item_50_4.context.contentLabel = this._query_Label_50_0.first;
    compView_50.create(this._Item_50_4.context,[
      ([] as any[]),
      ([] as any[]).concat([this._el_52]),
      ([] as any[]).concat([
        this._text_51,
        this._text_54,
        this._text_56
      ]
      ),
      ([] as any[]),
      ([] as any[]).concat([this._el_55])
    ]
    ,(null as any));
    this._text_57 = this.renderer.createText(this._el_48,'\n          ',(null as any));
    this._text_58 = this.renderer.createText(this._el_46,'\n        ',(null as any));
    this._text_59 = this.renderer.createText(this._el_15,'\n        ',(null as any));
    this._anchor_60 = this.renderer.createTemplateAnchor(this._el_15,(null as any));
    this._appEl_60 = new import3.AppElement(60,15,this,this._anchor_60);
    this._TemplateRef_60_5 = new import40.TemplateRef_(this._appEl_60,viewFactory_SpherePage1);
    this._NgIf_60_6 = new import26.Wrapper_NgIf(this._appEl_60.vcRef,this._TemplateRef_60_5);
    this._text_61 = this.renderer.createText(this._el_15,'\n        \n      ',(null as any));
    this._text_62 = this.renderer.createText(this._el_13,'\n    ',(null as any));
    this._text_63 = this.renderer.createText(this._el_11,'\n\n    ',(null as any));
    this._el_64 = this.renderer.createElement(this._el_11,'ion-footer',(null as any));
    this.renderer.setElementAttribute(this._el_64,'style','margin-bottom: 2em');
    this._Footer_64_3 = new import12.Wrapper_Footer(this.parentInjector.get(import27.Config),new import28.ElementRef(this._el_64),this.renderer,this.parentInjector.get(import29.ViewController,(null as any)));
    this._text_65 = this.renderer.createText(this._el_64,'\n      ',(null as any));
    this._el_66 = this.renderer.createElement(this._el_64,'ion-row',(null as any));
    this._Row_66_3 = new import16.Wrapper_Row();
    this._text_67 = this.renderer.createText(this._el_66,'\n        ',(null as any));
    this._el_68 = this.renderer.createElement(this._el_66,'ion-col',(null as any));
    this.renderer.setElementAttribute(this._el_68,'offset-10','');
    this.renderer.setElementAttribute(this._el_68,'width-80','');
    this._Col_68_3 = new import16.Wrapper_Col();
    this._text_69 = this.renderer.createText(this._el_68,'\n          ',(null as any));
    this._el_70 = this.renderer.createElement(this._el_68,'button',(null as any));
    this.renderer.setElementAttribute(this._el_70,'block','');
    this.renderer.setElementAttribute(this._el_70,'color','lens-dark');
    this.renderer.setElementAttribute(this._el_70,'ion-button','');
    this.renderer.setElementAttribute(this._el_70,'style','margin-bottom: 3em');
    this._appEl_70 = new import3.AppElement(70,68,this,this._el_70);
    var compView_70:any = import17.viewFactory_Button0(this.viewUtils,this.injector(70),this._appEl_70);
    this._Button_70_4 = new import17.Wrapper_Button((null as any),'',this.parentInjector.get(import27.Config),new import28.ElementRef(this._el_70),this.renderer);
    this._appEl_70.initComponent(this._Button_70_4.context,([] as any[]),compView_70);
    this._text_71 = this.renderer.createText((null as any),'Calculate',(null as any));
    compView_70.create(this._Button_70_4.context,[([] as any[]).concat([this._text_71])],(null as any));
    this._text_72 = this.renderer.createText(this._el_68,'\n          ',(null as any));
    this._el_73 = this.renderer.createElement(this._el_68,'hr',(null as any));
    this._text_74 = this.renderer.createText(this._el_68,'\n        ',(null as any));
    this._text_75 = this.renderer.createText(this._el_66,'\n      ',(null as any));
    this._text_76 = this.renderer.createText(this._el_64,'\n    ',(null as any));
    this._text_77 = this.renderer.createText(this._el_11,'\n  ',(null as any));
    this._text_78 = this.renderer.createText((null as any),'\n',(null as any));
    compView_9.create(this._Content_9_4.context,[
      ([] as any[]),
      ([] as any[]).concat([
        this._text_10,
        this._el_11,
        this._text_78
      ]
      ),
      ([] as any[])
    ]
    ,(null as any));
    this._expr_1 = import7.UNINITIALIZED;
    this._expr_2 = import7.UNINITIALIZED;
    this._expr_3 = import7.UNINITIALIZED;
    var disposable_0:Function = this.renderer.listen(this._el_26,'click',this.eventHandler(this._handle_click_26_0.bind(this)));
    this._expr_8 = import7.UNINITIALIZED;
    var disposable_1:Function = this.renderer.listen(this._el_34,'ngModelChange',this.eventHandler(this._handle_ngModelChange_34_0.bind(this)));
    const subscription_0:any = this._NgModel_34_4.context.update.subscribe(this.eventHandler(this._handle_ngModelChange_34_0.bind(this)));
    this._expr_11 = import7.UNINITIALIZED;
    this._expr_12 = import7.UNINITIALIZED;
    this._expr_13 = import7.UNINITIALIZED;
    this._expr_14 = import7.UNINITIALIZED;
    this._expr_15 = import7.UNINITIALIZED;
    this._expr_16 = import7.UNINITIALIZED;
    var disposable_2:Function = this.renderer.listen(this._el_39,'click',this.eventHandler(this._handle_click_39_0.bind(this)));
    this._expr_22 = import7.UNINITIALIZED;
    var disposable_3:Function = this.renderer.listen(this._el_55,'ngModelChange',this.eventHandler(this._handle_ngModelChange_55_0.bind(this)));
    this._expr_25 = import7.UNINITIALIZED;
    const subscription_1:any = this._NgModel_55_6.context.update.subscribe(this.eventHandler(this._handle_ngModelChange_55_0.bind(this)));
    this._expr_27 = import7.UNINITIALIZED;
    this._expr_28 = import7.UNINITIALIZED;
    this._expr_29 = import7.UNINITIALIZED;
    this._expr_30 = import7.UNINITIALIZED;
    this._expr_31 = import7.UNINITIALIZED;
    this._expr_32 = import7.UNINITIALIZED;
    var disposable_4:Function = this.renderer.listen(this._el_70,'click',this.eventHandler(this._handle_click_70_0.bind(this)));
    this.init(([] as any[]),[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._text_6,
      this._text_7,
      this._text_8,
      this._el_9,
      this._text_10,
      this._el_11,
      this._text_12,
      this._el_13,
      this._text_14,
      this._el_15,
      this._text_16,
      this._el_17,
      this._text_18,
      this._text_19,
      this._el_20,
      this._text_21,
      this._el_22,
      this._text_23,
      this._el_24,
      this._text_25,
      this._el_26,
      this._text_27,
      this._el_28,
      this._text_29,
      this._text_30,
      this._text_31,
      this._el_32,
      this._text_33,
      this._el_34,
      this._text_35,
      this._text_36,
      this._el_37,
      this._text_38,
      this._el_39,
      this._text_40,
      this._el_41,
      this._text_42,
      this._text_43,
      this._text_44,
      this._text_45,
      this._el_46,
      this._text_47,
      this._el_48,
      this._text_49,
      this._el_50,
      this._text_51,
      this._el_52,
      this._text_53,
      this._text_54,
      this._el_55,
      this._text_56,
      this._text_57,
      this._text_58,
      this._text_59,
      this._anchor_60,
      this._text_61,
      this._text_62,
      this._text_63,
      this._el_64,
      this._text_65,
      this._el_66,
      this._text_67,
      this._el_68,
      this._text_69,
      this._el_70,
      this._text_71,
      this._text_72,
      this._el_73,
      this._text_74,
      this._text_75,
      this._text_76,
      this._text_77,
      this._text_78
    ]
    ,[
      disposable_0,
      disposable_1,
      disposable_2,
      disposable_3,
      disposable_4
    ]
    ,[
      subscription_0,
      subscription_1
    ]
    );
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import41.ToolbarTitle) && ((4 <= requestNodeIndex) && (requestNodeIndex <= 5)))) { return this._ToolbarTitle_4_4.context; }
    if (((token === import42.Navbar) && ((2 <= requestNodeIndex) && (requestNodeIndex <= 6)))) { return this._Navbar_2_4.context; }
    if (((token === import31.Header) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 7)))) { return this._Header_0_3.context; }
    if (((token === import43.Icon) && (28 === requestNodeIndex))) { return this._Icon_28_3.context; }
    if (((token === import44.Button) && ((26 <= requestNodeIndex) && (requestNodeIndex <= 29)))) { return this._Button_26_4.context; }
    if (((token === import45.Col) && ((24 <= requestNodeIndex) && (requestNodeIndex <= 30)))) { return this._Col_24_3.context; }
    if (((token === import46.NgModel) && (34 === requestNodeIndex))) { return this._NgModel_34_4.context; }
    if (((token === import47.NgControl) && (34 === requestNodeIndex))) { return this._NgControl_34_5; }
    if (((token === import48.NgControlStatus) && (34 === requestNodeIndex))) { return this._NgControlStatus_34_6.context; }
    if (((token === import49.TextInput) && (34 === requestNodeIndex))) { return this._TextInput_34_7.context; }
    if (((token === import45.Col) && ((32 <= requestNodeIndex) && (requestNodeIndex <= 35)))) { return this._Col_32_3.context; }
    if (((token === import43.Icon) && (41 === requestNodeIndex))) { return this._Icon_41_3.context; }
    if (((token === import44.Button) && ((39 <= requestNodeIndex) && (requestNodeIndex <= 42)))) { return this._Button_39_4.context; }
    if (((token === import45.Col) && ((37 <= requestNodeIndex) && (requestNodeIndex <= 43)))) { return this._Col_37_3.context; }
    if (((token === import45.Row) && ((22 <= requestNodeIndex) && (requestNodeIndex <= 44)))) { return this._Row_22_3.context; }
    if (((token === import50.Label) && ((52 <= requestNodeIndex) && (requestNodeIndex <= 53)))) { return this._Label_52_3.context; }
    if (((token === import51.Toggle) && (55 === requestNodeIndex))) { return this._Toggle_55_4.context; }
    if (((token === import52.NG_VALUE_ACCESSOR) && (55 === requestNodeIndex))) { return this._NG_VALUE_ACCESSOR_55_5; }
    if (((token === import46.NgModel) && (55 === requestNodeIndex))) { return this._NgModel_55_6.context; }
    if (((token === import47.NgControl) && (55 === requestNodeIndex))) { return this._NgControl_55_7; }
    if (((token === import48.NgControlStatus) && (55 === requestNodeIndex))) { return this._NgControlStatus_55_8.context; }
    if (((token === import36.Item) && ((50 <= requestNodeIndex) && (requestNodeIndex <= 56)))) { return this._Item_50_4.context; }
    if (((token === import36.ItemContent) && ((50 <= requestNodeIndex) && (requestNodeIndex <= 56)))) { return this._ItemContent_50_5.context; }
    if (((token === import45.Col) && ((48 <= requestNodeIndex) && (requestNodeIndex <= 57)))) { return this._Col_48_3.context; }
    if (((token === import45.Row) && ((46 <= requestNodeIndex) && (requestNodeIndex <= 58)))) { return this._Row_46_3.context; }
    if (((token === import40.TemplateRef) && (60 === requestNodeIndex))) { return this._TemplateRef_60_5; }
    if (((token === import53.NgIf) && (60 === requestNodeIndex))) { return this._NgIf_60_6.context; }
    if (((token === import45.Col) && ((15 <= requestNodeIndex) && (requestNodeIndex <= 61)))) { return this._Col_15_3.context; }
    if (((token === import45.Row) && ((13 <= requestNodeIndex) && (requestNodeIndex <= 62)))) { return this._Row_13_3.context; }
    if (((token === import44.Button) && ((70 <= requestNodeIndex) && (requestNodeIndex <= 71)))) { return this._Button_70_4.context; }
    if (((token === import45.Col) && ((68 <= requestNodeIndex) && (requestNodeIndex <= 74)))) { return this._Col_68_3.context; }
    if (((token === import45.Row) && ((66 <= requestNodeIndex) && (requestNodeIndex <= 75)))) { return this._Row_66_3.context; }
    if (((token === import31.Footer) && ((64 <= requestNodeIndex) && (requestNodeIndex <= 76)))) { return this._Footer_64_3.context; }
    if (((token === import45.Grid) && ((11 <= requestNodeIndex) && (requestNodeIndex <= 77)))) { return this._Grid_11_3.context; }
    if (((token === import54.Content) && ((9 <= requestNodeIndex) && (requestNodeIndex <= 78)))) { return this._Content_9_4.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._Header_0_3.detectChangesInternal(this,this._el_0,throwOnChange);
    const currVal_0:any = 'lens-dark';
    this._Navbar_2_4.check_color(currVal_0,throwOnChange,false);
    this._Navbar_2_4.detectChangesInternal(this,this._el_2,throwOnChange);
    if (this._ToolbarTitle_4_4.detectChangesInternal(this,this._el_4,throwOnChange)) { this._appEl_4.componentView.markAsCheckOnce(); }
    if (this._Content_9_4.detectChangesInternal(this,this._el_9,throwOnChange)) { this._appEl_9.componentView.markAsCheckOnce(); }
    this._Grid_11_3.detectChangesInternal(this,this._el_11,throwOnChange);
    this._Row_13_3.detectChangesInternal(this,this._el_13,throwOnChange);
    this._Col_15_3.detectChangesInternal(this,this._el_15,throwOnChange);
    this._Row_22_3.detectChangesInternal(this,this._el_22,throwOnChange);
    this._Col_24_3.detectChangesInternal(this,this._el_24,throwOnChange);
    const currVal_5:any = '';
    this._Button_26_4.check_clear(currVal_5,throwOnChange,false);
    const currVal_6:any = 'lens-light';
    this._Button_26_4.check_color(currVal_6,throwOnChange,false);
    if (this._Button_26_4.detectChangesInternal(this,this._el_26,throwOnChange)) { this._appEl_26.componentView.markAsCheckOnce(); }
    const currVal_7:any = 'remove';
    this._Icon_28_3.check_name(currVal_7,throwOnChange,false);
    this._Icon_28_3.detectChangesInternal(this,this._el_28,throwOnChange);
    this._Col_32_3.detectChangesInternal(this,this._el_32,throwOnChange);
    const currVal_10:any = this.context.pLens.prescription;
    this._NgModel_34_4.check_model(currVal_10,throwOnChange,false);
    this._NgModel_34_4.detectChangesInternal(this,this._el_34,throwOnChange);
    this._NgControlStatus_34_6.detectChangesInternal(this,this._el_34,throwOnChange);
    const currVal_17:any = 'number';
    this._TextInput_34_7.check_type(currVal_17,throwOnChange,false);
    this._TextInput_34_7.detectChangesInternal(this,this._el_34,throwOnChange);
    this._Col_37_3.detectChangesInternal(this,this._el_37,throwOnChange);
    const currVal_19:any = '';
    this._Button_39_4.check_clear(currVal_19,throwOnChange,false);
    const currVal_20:any = 'lens-light';
    this._Button_39_4.check_color(currVal_20,throwOnChange,false);
    if (this._Button_39_4.detectChangesInternal(this,this._el_39,throwOnChange)) { this._appEl_39.componentView.markAsCheckOnce(); }
    const currVal_21:any = 'add';
    this._Icon_41_3.check_name(currVal_21,throwOnChange,false);
    this._Icon_41_3.detectChangesInternal(this,this._el_41,throwOnChange);
    this._Row_46_3.detectChangesInternal(this,this._el_46,throwOnChange);
    this._Col_48_3.detectChangesInternal(this,this._el_48,throwOnChange);
    if (this._Item_50_4.detectChangesInternal(this,this._el_50,throwOnChange)) { this._appEl_50.componentView.markAsCheckOnce(); }
    this._ItemContent_50_5.detectChangesInternal(this,this._el_50,throwOnChange);
    this._Label_52_3.detectChangesInternal(this,this._el_52,throwOnChange);
    const currVal_24:any = 'lens-light';
    this._Toggle_55_4.check_color(currVal_24,throwOnChange,false);
    this._Toggle_55_4.detectChangesInternal(this,this._el_55,throwOnChange);
    const currVal_26:any = this.context.pLens.hasAstigmatism;
    this._NgModel_55_6.check_model(currVal_26,throwOnChange,false);
    this._NgModel_55_6.detectChangesInternal(this,this._el_55,throwOnChange);
    this._NgControlStatus_55_8.detectChangesInternal(this,this._el_55,throwOnChange);
    const currVal_33:any = this.context.pLens.hasAstigmatism;
    this._NgIf_60_6.check_ngIf(currVal_33,throwOnChange,false);
    this._NgIf_60_6.detectChangesInternal(this,this._anchor_60,throwOnChange);
    this._Footer_64_3.detectChangesInternal(this,this._el_64,throwOnChange);
    this._Row_66_3.detectChangesInternal(this,this._el_66,throwOnChange);
    this._Col_68_3.detectChangesInternal(this,this._el_68,throwOnChange);
    const currVal_35:any = '';
    this._Button_70_4.check_block(currVal_35,throwOnChange,false);
    const currVal_36:any = 'lens-dark';
    this._Button_70_4.check_color(currVal_36,throwOnChange,false);
    if (this._Button_70_4.detectChangesInternal(this,this._el_70,throwOnChange)) { this._appEl_70.componentView.markAsCheckOnce(); }
    this.detectContentChildrenChanges(throwOnChange);
    if (!throwOnChange) {
      if (this._query_Button_50_1.dirty) {
        this._query_Button_50_1.reset(([] as any[]));
        this._Item_50_4.context._buttons = this._query_Button_50_1;
        this._query_Button_50_1.notifyOnChanges();
      }
      if (this._query_Icon_50_2.dirty) {
        this._query_Icon_50_2.reset(([] as any[]));
        this._Item_50_4.context._icons = this._query_Icon_50_2;
        this._query_Icon_50_2.notifyOnChanges();
      }
      if ((this.numberOfChecks === 0)) { this._Button_26_4.context.ngAfterContentInit(); }
      this._TextInput_34_7.context.ngAfterContentChecked();
      if ((this.numberOfChecks === 0)) { this._Button_39_4.context.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Toggle_55_4.context.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Item_50_4.context.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Button_70_4.context.ngAfterContentInit(); }
    }
    const currVal_1:any = this._Navbar_2_4.context._hidden;
    if (import4.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this.renderer.setElementProperty(this._el_2,'hidden',currVal_1);
      this._expr_1 = currVal_1;
    }
    const currVal_2:any = this._Navbar_2_4.context._sbPadding;
    if (import4.checkBinding(throwOnChange,this._expr_2,currVal_2)) {
      this.renderer.setElementClass(this._el_2,'statusbar-padding',currVal_2);
      this._expr_2 = currVal_2;
    }
    const currVal_3:any = this._Content_9_4.context._sbPadding;
    if (import4.checkBinding(throwOnChange,this._expr_3,currVal_3)) {
      this.renderer.setElementClass(this._el_9,'statusbar-padding',currVal_3);
      this._expr_3 = currVal_3;
    }
    const currVal_8:any = this._Icon_28_3.context._hidden;
    if (import4.checkBinding(throwOnChange,this._expr_8,currVal_8)) {
      this.renderer.setElementClass(this._el_28,'hide',currVal_8);
      this._expr_8 = currVal_8;
    }
    const currVal_11:any = this._NgControlStatus_34_6.context.ngClassUntouched;
    if (import4.checkBinding(throwOnChange,this._expr_11,currVal_11)) {
      this.renderer.setElementClass(this._el_34,'ng-untouched',currVal_11);
      this._expr_11 = currVal_11;
    }
    const currVal_12:any = this._NgControlStatus_34_6.context.ngClassTouched;
    if (import4.checkBinding(throwOnChange,this._expr_12,currVal_12)) {
      this.renderer.setElementClass(this._el_34,'ng-touched',currVal_12);
      this._expr_12 = currVal_12;
    }
    const currVal_13:any = this._NgControlStatus_34_6.context.ngClassPristine;
    if (import4.checkBinding(throwOnChange,this._expr_13,currVal_13)) {
      this.renderer.setElementClass(this._el_34,'ng-pristine',currVal_13);
      this._expr_13 = currVal_13;
    }
    const currVal_14:any = this._NgControlStatus_34_6.context.ngClassDirty;
    if (import4.checkBinding(throwOnChange,this._expr_14,currVal_14)) {
      this.renderer.setElementClass(this._el_34,'ng-dirty',currVal_14);
      this._expr_14 = currVal_14;
    }
    const currVal_15:any = this._NgControlStatus_34_6.context.ngClassValid;
    if (import4.checkBinding(throwOnChange,this._expr_15,currVal_15)) {
      this.renderer.setElementClass(this._el_34,'ng-valid',currVal_15);
      this._expr_15 = currVal_15;
    }
    const currVal_16:any = this._NgControlStatus_34_6.context.ngClassInvalid;
    if (import4.checkBinding(throwOnChange,this._expr_16,currVal_16)) {
      this.renderer.setElementClass(this._el_34,'ng-invalid',currVal_16);
      this._expr_16 = currVal_16;
    }
    const currVal_22:any = this._Icon_41_3.context._hidden;
    if (import4.checkBinding(throwOnChange,this._expr_22,currVal_22)) {
      this.renderer.setElementClass(this._el_41,'hide',currVal_22);
      this._expr_22 = currVal_22;
    }
    const currVal_25:any = this._Toggle_55_4.context._disabled;
    if (import4.checkBinding(throwOnChange,this._expr_25,currVal_25)) {
      this.renderer.setElementClass(this._el_55,'toggle-disabled',currVal_25);
      this._expr_25 = currVal_25;
    }
    const currVal_27:any = this._NgControlStatus_55_8.context.ngClassUntouched;
    if (import4.checkBinding(throwOnChange,this._expr_27,currVal_27)) {
      this.renderer.setElementClass(this._el_55,'ng-untouched',currVal_27);
      this._expr_27 = currVal_27;
    }
    const currVal_28:any = this._NgControlStatus_55_8.context.ngClassTouched;
    if (import4.checkBinding(throwOnChange,this._expr_28,currVal_28)) {
      this.renderer.setElementClass(this._el_55,'ng-touched',currVal_28);
      this._expr_28 = currVal_28;
    }
    const currVal_29:any = this._NgControlStatus_55_8.context.ngClassPristine;
    if (import4.checkBinding(throwOnChange,this._expr_29,currVal_29)) {
      this.renderer.setElementClass(this._el_55,'ng-pristine',currVal_29);
      this._expr_29 = currVal_29;
    }
    const currVal_30:any = this._NgControlStatus_55_8.context.ngClassDirty;
    if (import4.checkBinding(throwOnChange,this._expr_30,currVal_30)) {
      this.renderer.setElementClass(this._el_55,'ng-dirty',currVal_30);
      this._expr_30 = currVal_30;
    }
    const currVal_31:any = this._NgControlStatus_55_8.context.ngClassValid;
    if (import4.checkBinding(throwOnChange,this._expr_31,currVal_31)) {
      this.renderer.setElementClass(this._el_55,'ng-valid',currVal_31);
      this._expr_31 = currVal_31;
    }
    const currVal_32:any = this._NgControlStatus_55_8.context.ngClassInvalid;
    if (import4.checkBinding(throwOnChange,this._expr_32,currVal_32)) {
      this.renderer.setElementClass(this._el_55,'ng-invalid',currVal_32);
      this._expr_32 = currVal_32;
    }
    this.detectViewChildrenChanges(throwOnChange);
    if (!throwOnChange) { if ((this.numberOfChecks === 0)) { this._Navbar_2_4.context.ngAfterViewInit(); } }
  }
  destroyInternal():void {
    this._Icon_28_3.context.ngOnDestroy();
    this._NgModel_34_4.context.ngOnDestroy();
    this._TextInput_34_7.context.ngOnDestroy();
    this._Icon_41_3.context.ngOnDestroy();
    this._Toggle_55_4.context.ngOnDestroy();
    this._NgModel_55_6.context.ngOnDestroy();
    this._Content_9_4.context.ngOnDestroy();
  }
  private _handle_click_26_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.dec()) !== false);
    return (true && pd_0);
  }
  private _handle_ngModelChange_34_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>(this.context.pLens.prescription = $event)) !== false);
    return (true && pd_0);
  }
  private _handle_click_39_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.inc()) !== false);
    return (true && pd_0);
  }
  private _handle_ngModelChange_55_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>(this.context.pLens.hasAstigmatism = $event)) !== false);
    return (true && pd_0);
  }
  private _handle_click_70_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.calculate()) !== false);
    return (true && pd_0);
  }
}
export function viewFactory_SpherePage0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement):import1.AppView<import0.SpherePage> {
  if ((renderType_SpherePage === (null as any))) { (renderType_SpherePage = viewUtils.createRenderComponentType('',0,import10.ViewEncapsulation.None,styles_SpherePage,{})); }
  return new _View_SpherePage0(viewUtils,parentInjector,declarationEl);
}
class _View_SpherePage1 extends import1.AppView<any> {
  _el_0:any;
  _Row_0_3:import16.Wrapper_Row;
  _text_1:any;
  _el_2:any;
  _Col_2_3:import16.Wrapper_Col;
  _text_3:any;
  _el_4:any;
  /*private*/ _appEl_4:import3.AppElement;
  _Button_4_4:import17.Wrapper_Button;
  _text_5:any;
  _el_6:any;
  _Icon_6_3:import18.Wrapper_Icon;
  _text_7:any;
  _text_8:any;
  _text_9:any;
  _el_10:any;
  _Col_10_3:import16.Wrapper_Col;
  _text_11:any;
  _el_12:any;
  /*private*/ _appEl_12:import3.AppElement;
  _NgModel_12_4:import19.Wrapper_NgModel;
  _NgControl_12_5:any;
  _NgControlStatus_12_6:import20.Wrapper_NgControlStatus;
  _TextInput_12_7:import21.Wrapper_TextInput;
  _text_13:any;
  _text_14:any;
  _el_15:any;
  _Col_15_3:import16.Wrapper_Col;
  _text_16:any;
  _el_17:any;
  /*private*/ _appEl_17:import3.AppElement;
  _Button_17_4:import17.Wrapper_Button;
  _text_18:any;
  _el_19:any;
  _Icon_19_3:import18.Wrapper_Icon;
  _text_20:any;
  _text_21:any;
  _text_22:any;
  /*private*/ _expr_4:any;
  /*private*/ _expr_7:any;
  /*private*/ _expr_8:any;
  /*private*/ _expr_9:any;
  /*private*/ _expr_10:any;
  /*private*/ _expr_11:any;
  /*private*/ _expr_12:any;
  /*private*/ _expr_18:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement) {
    super(_View_SpherePage1,renderType_SpherePage,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'ion-row',(null as any));
    this._Row_0_3 = new import16.Wrapper_Row();
    this._text_1 = this.renderer.createText(this._el_0,'\n          ',(null as any));
    this._el_2 = this.renderer.createElement(this._el_0,'ion-col',(null as any));
    this.renderer.setElementAttribute(this._el_2,'center','');
    this.renderer.setElementAttribute(this._el_2,'text-right','');
    this.renderer.setElementAttribute(this._el_2,'width-25','');
    this._Col_2_3 = new import16.Wrapper_Col();
    this._text_3 = this.renderer.createText(this._el_2,'\n            ',(null as any));
    this._el_4 = this.renderer.createElement(this._el_2,'button',(null as any));
    this.renderer.setElementAttribute(this._el_4,'clear','');
    this.renderer.setElementAttribute(this._el_4,'color','lens-light');
    this.renderer.setElementAttribute(this._el_4,'ion-button','');
    this._appEl_4 = new import3.AppElement(4,2,this,this._el_4);
    var compView_4:any = import17.viewFactory_Button0(this.viewUtils,this.injector(4),this._appEl_4);
    this._Button_4_4 = new import17.Wrapper_Button((null as any),'',this.parent.parentInjector.get(import27.Config),new import28.ElementRef(this._el_4),this.renderer);
    this._appEl_4.initComponent(this._Button_4_4.context,([] as any[]),compView_4);
    this._text_5 = this.renderer.createText((null as any),'\n              ',(null as any));
    this._el_6 = this.renderer.createElement((null as any),'ion-icon',(null as any));
    this.renderer.setElementAttribute(this._el_6,'name','remove');
    this.renderer.setElementAttribute(this._el_6,'role','img');
    this._Icon_6_3 = new import18.Wrapper_Icon(this.parent.parentInjector.get(import27.Config),new import28.ElementRef(this._el_6),this.renderer);
    this._text_7 = this.renderer.createText((null as any),'\n            ',(null as any));
      compView_4.create(this._Button_4_4.context,[([] as any[]).concat([
        this._text_5,
        this._el_6,
        this._text_7
      ]
    )],(null as any));
    this._text_8 = this.renderer.createText(this._el_2,'\n          ',(null as any));
    this._text_9 = this.renderer.createText(this._el_0,'\n          ',(null as any));
    this._el_10 = this.renderer.createElement(this._el_0,'ion-col',(null as any));
    this.renderer.setElementAttribute(this._el_10,'center','');
    this.renderer.setElementAttribute(this._el_10,'style','font-size: 2em');
    this.renderer.setElementAttribute(this._el_10,'width-50','');
    this._Col_10_3 = new import16.Wrapper_Col();
    this._text_11 = this.renderer.createText(this._el_10,'\n            ',(null as any));
    this._el_12 = this.renderer.createElement(this._el_10,'ion-input',(null as any));
    this.renderer.setElementAttribute(this._el_12,'text-center','');
    this.renderer.setElementAttribute(this._el_12,'type','number');
    this._appEl_12 = new import3.AppElement(12,10,this,this._el_12);
    var compView_12:any = import21.viewFactory_TextInput0(this.viewUtils,this.injector(12),this._appEl_12);
    this._NgModel_12_4 = new import19.Wrapper_NgModel((null as any),(null as any),(null as any),(null as any));
    this._NgControl_12_5 = this._NgModel_12_4.context;
    this._NgControlStatus_12_6 = new import20.Wrapper_NgControlStatus(this._NgControl_12_5);
    this._TextInput_12_7 = new import21.Wrapper_TextInput(this.parent.parentInjector.get(import27.Config),this.parent.parentInjector.get(import35.Form),this.parent.parentInjector.get(import36.Item,(null as any)),this.parent.parentInjector.get(import30.App),this.parent.parentInjector.get(import37.Platform),new import28.ElementRef(this._el_12),this.renderer,(<_View_SpherePage0>this.parent)._Content_9_4.context,this.parent.parentInjector.get(import8.NavController,(null as any)),this._NgControl_12_5);
    this._appEl_12.initComponent(this._TextInput_12_7.context,([] as any[]),compView_12);
    compView_12.create(this._TextInput_12_7.context,([] as any[]),(null as any));
    this._text_13 = this.renderer.createText(this._el_10,'\n          ',(null as any));
    this._text_14 = this.renderer.createText(this._el_0,'\n          ',(null as any));
    this._el_15 = this.renderer.createElement(this._el_0,'ion-col',(null as any));
    this.renderer.setElementAttribute(this._el_15,'center','');
    this.renderer.setElementAttribute(this._el_15,'text-left','');
    this.renderer.setElementAttribute(this._el_15,'width-25','');
    this._Col_15_3 = new import16.Wrapper_Col();
    this._text_16 = this.renderer.createText(this._el_15,'\n            ',(null as any));
    this._el_17 = this.renderer.createElement(this._el_15,'button',(null as any));
    this.renderer.setElementAttribute(this._el_17,'clear','');
    this.renderer.setElementAttribute(this._el_17,'color','lens-light');
    this.renderer.setElementAttribute(this._el_17,'ion-button','');
    this._appEl_17 = new import3.AppElement(17,15,this,this._el_17);
    var compView_17:any = import17.viewFactory_Button0(this.viewUtils,this.injector(17),this._appEl_17);
    this._Button_17_4 = new import17.Wrapper_Button((null as any),'',this.parent.parentInjector.get(import27.Config),new import28.ElementRef(this._el_17),this.renderer);
    this._appEl_17.initComponent(this._Button_17_4.context,([] as any[]),compView_17);
    this._text_18 = this.renderer.createText((null as any),'\n              ',(null as any));
    this._el_19 = this.renderer.createElement((null as any),'ion-icon',(null as any));
    this.renderer.setElementAttribute(this._el_19,'name','add');
    this.renderer.setElementAttribute(this._el_19,'role','img');
    this._Icon_19_3 = new import18.Wrapper_Icon(this.parent.parentInjector.get(import27.Config),new import28.ElementRef(this._el_19),this.renderer);
    this._text_20 = this.renderer.createText((null as any),'\n            ',(null as any));
      compView_17.create(this._Button_17_4.context,[([] as any[]).concat([
        this._text_18,
        this._el_19,
        this._text_20
      ]
    )],(null as any));
    this._text_21 = this.renderer.createText(this._el_15,'\n          ',(null as any));
    this._text_22 = this.renderer.createText(this._el_0,'\n        ',(null as any));
    var disposable_0:Function = this.renderer.listen(this._el_4,'click',this.eventHandler(this._handle_click_4_0.bind(this)));
    this._expr_4 = import7.UNINITIALIZED;
    var disposable_1:Function = this.renderer.listen(this._el_12,'ngModelChange',this.eventHandler(this._handle_ngModelChange_12_0.bind(this)));
    const subscription_0:any = this._NgModel_12_4.context.update.subscribe(this.eventHandler(this._handle_ngModelChange_12_0.bind(this)));
    this._expr_7 = import7.UNINITIALIZED;
    this._expr_8 = import7.UNINITIALIZED;
    this._expr_9 = import7.UNINITIALIZED;
    this._expr_10 = import7.UNINITIALIZED;
    this._expr_11 = import7.UNINITIALIZED;
    this._expr_12 = import7.UNINITIALIZED;
    var disposable_2:Function = this.renderer.listen(this._el_17,'click',this.eventHandler(this._handle_click_17_0.bind(this)));
    this._expr_18 = import7.UNINITIALIZED;
    this.init(([] as any[]).concat([this._el_0]),[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._el_6,
      this._text_7,
      this._text_8,
      this._text_9,
      this._el_10,
      this._text_11,
      this._el_12,
      this._text_13,
      this._text_14,
      this._el_15,
      this._text_16,
      this._el_17,
      this._text_18,
      this._el_19,
      this._text_20,
      this._text_21,
      this._text_22
    ]
    ,[
      disposable_0,
      disposable_1,
      disposable_2
    ]
    ,[subscription_0]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import43.Icon) && (6 === requestNodeIndex))) { return this._Icon_6_3.context; }
    if (((token === import44.Button) && ((4 <= requestNodeIndex) && (requestNodeIndex <= 7)))) { return this._Button_4_4.context; }
    if (((token === import45.Col) && ((2 <= requestNodeIndex) && (requestNodeIndex <= 8)))) { return this._Col_2_3.context; }
    if (((token === import46.NgModel) && (12 === requestNodeIndex))) { return this._NgModel_12_4.context; }
    if (((token === import47.NgControl) && (12 === requestNodeIndex))) { return this._NgControl_12_5; }
    if (((token === import48.NgControlStatus) && (12 === requestNodeIndex))) { return this._NgControlStatus_12_6.context; }
    if (((token === import49.TextInput) && (12 === requestNodeIndex))) { return this._TextInput_12_7.context; }
    if (((token === import45.Col) && ((10 <= requestNodeIndex) && (requestNodeIndex <= 13)))) { return this._Col_10_3.context; }
    if (((token === import43.Icon) && (19 === requestNodeIndex))) { return this._Icon_19_3.context; }
    if (((token === import44.Button) && ((17 <= requestNodeIndex) && (requestNodeIndex <= 20)))) { return this._Button_17_4.context; }
    if (((token === import45.Col) && ((15 <= requestNodeIndex) && (requestNodeIndex <= 21)))) { return this._Col_15_3.context; }
    if (((token === import45.Row) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 22)))) { return this._Row_0_3.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._Row_0_3.detectChangesInternal(this,this._el_0,throwOnChange);
    this._Col_2_3.detectChangesInternal(this,this._el_2,throwOnChange);
    const currVal_1:any = '';
    this._Button_4_4.check_clear(currVal_1,throwOnChange,false);
    const currVal_2:any = 'lens-light';
    this._Button_4_4.check_color(currVal_2,throwOnChange,false);
    if (this._Button_4_4.detectChangesInternal(this,this._el_4,throwOnChange)) { this._appEl_4.componentView.markAsCheckOnce(); }
    const currVal_3:any = 'remove';
    this._Icon_6_3.check_name(currVal_3,throwOnChange,false);
    this._Icon_6_3.detectChangesInternal(this,this._el_6,throwOnChange);
    this._Col_10_3.detectChangesInternal(this,this._el_10,throwOnChange);
    const currVal_6:any = this.parent.context.pLens.astigmatismValue;
    this._NgModel_12_4.check_model(currVal_6,throwOnChange,false);
    this._NgModel_12_4.detectChangesInternal(this,this._el_12,throwOnChange);
    this._NgControlStatus_12_6.detectChangesInternal(this,this._el_12,throwOnChange);
    const currVal_13:any = 'number';
    this._TextInput_12_7.check_type(currVal_13,throwOnChange,false);
    this._TextInput_12_7.detectChangesInternal(this,this._el_12,throwOnChange);
    this._Col_15_3.detectChangesInternal(this,this._el_15,throwOnChange);
    const currVal_15:any = '';
    this._Button_17_4.check_clear(currVal_15,throwOnChange,false);
    const currVal_16:any = 'lens-light';
    this._Button_17_4.check_color(currVal_16,throwOnChange,false);
    if (this._Button_17_4.detectChangesInternal(this,this._el_17,throwOnChange)) { this._appEl_17.componentView.markAsCheckOnce(); }
    const currVal_17:any = 'add';
    this._Icon_19_3.check_name(currVal_17,throwOnChange,false);
    this._Icon_19_3.detectChangesInternal(this,this._el_19,throwOnChange);
    this.detectContentChildrenChanges(throwOnChange);
    if (!throwOnChange) {
      if ((this.numberOfChecks === 0)) { this._Button_4_4.context.ngAfterContentInit(); }
      this._TextInput_12_7.context.ngAfterContentChecked();
      if ((this.numberOfChecks === 0)) { this._Button_17_4.context.ngAfterContentInit(); }
    }
    const currVal_4:any = this._Icon_6_3.context._hidden;
    if (import4.checkBinding(throwOnChange,this._expr_4,currVal_4)) {
      this.renderer.setElementClass(this._el_6,'hide',currVal_4);
      this._expr_4 = currVal_4;
    }
    const currVal_7:any = this._NgControlStatus_12_6.context.ngClassUntouched;
    if (import4.checkBinding(throwOnChange,this._expr_7,currVal_7)) {
      this.renderer.setElementClass(this._el_12,'ng-untouched',currVal_7);
      this._expr_7 = currVal_7;
    }
    const currVal_8:any = this._NgControlStatus_12_6.context.ngClassTouched;
    if (import4.checkBinding(throwOnChange,this._expr_8,currVal_8)) {
      this.renderer.setElementClass(this._el_12,'ng-touched',currVal_8);
      this._expr_8 = currVal_8;
    }
    const currVal_9:any = this._NgControlStatus_12_6.context.ngClassPristine;
    if (import4.checkBinding(throwOnChange,this._expr_9,currVal_9)) {
      this.renderer.setElementClass(this._el_12,'ng-pristine',currVal_9);
      this._expr_9 = currVal_9;
    }
    const currVal_10:any = this._NgControlStatus_12_6.context.ngClassDirty;
    if (import4.checkBinding(throwOnChange,this._expr_10,currVal_10)) {
      this.renderer.setElementClass(this._el_12,'ng-dirty',currVal_10);
      this._expr_10 = currVal_10;
    }
    const currVal_11:any = this._NgControlStatus_12_6.context.ngClassValid;
    if (import4.checkBinding(throwOnChange,this._expr_11,currVal_11)) {
      this.renderer.setElementClass(this._el_12,'ng-valid',currVal_11);
      this._expr_11 = currVal_11;
    }
    const currVal_12:any = this._NgControlStatus_12_6.context.ngClassInvalid;
    if (import4.checkBinding(throwOnChange,this._expr_12,currVal_12)) {
      this.renderer.setElementClass(this._el_12,'ng-invalid',currVal_12);
      this._expr_12 = currVal_12;
    }
    const currVal_18:any = this._Icon_19_3.context._hidden;
    if (import4.checkBinding(throwOnChange,this._expr_18,currVal_18)) {
      this.renderer.setElementClass(this._el_19,'hide',currVal_18);
      this._expr_18 = currVal_18;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
  destroyInternal():void {
    this._Icon_6_3.context.ngOnDestroy();
    this._NgModel_12_4.context.ngOnDestroy();
    this._TextInput_12_7.context.ngOnDestroy();
    this._Icon_19_3.context.ngOnDestroy();
  }
  private _handle_click_4_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.parent.context.decA()) !== false);
    return (true && pd_0);
  }
  private _handle_ngModelChange_12_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>(this.parent.context.pLens.astigmatismValue = $event)) !== false);
    return (true && pd_0);
  }
  private _handle_click_17_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.parent.context.incA()) !== false);
    return (true && pd_0);
  }
}
function viewFactory_SpherePage1(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement):import1.AppView<any> {
  return new _View_SpherePage1(viewUtils,parentInjector,declarationEl);
}