/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from './confirmation';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/render/api';
import * as import3 from '@angular/core/src/linker/element';
import * as import4 from '@angular/core/src/linker/view_utils';
import * as import5 from '@angular/core/src/di/injector';
import * as import6 from '@angular/core/src/linker/view_type';
import * as import7 from '@angular/core/src/change_detection/change_detection';
import * as import8 from 'ionic-angular/navigation/nav-controller';
import * as import9 from 'ionic-angular/components/alert/alert';
import * as import10 from '@angular/core/src/metadata/view';
import * as import11 from '@angular/core/src/linker/component_factory';
import * as import12 from '../../node_modules/ionic-angular/components/toolbar/toolbar.ngfactory';
import * as import13 from '../../node_modules/ionic-angular/components/navbar/navbar.ngfactory';
import * as import14 from '../../node_modules/ionic-angular/components/toolbar/toolbar-title.ngfactory';
import * as import15 from '../../node_modules/ionic-angular/components/content/content.ngfactory';
import * as import16 from '../../node_modules/ionic-angular/components/grid/grid.ngfactory';
import * as import17 from '../../node_modules/ionic-angular/components/card/card.ngfactory';
import * as import18 from '../../node_modules/ionic-angular/components/button/button.ngfactory';
import * as import19 from 'ionic-angular/config/config';
import * as import20 from '@angular/core/src/linker/element_ref';
import * as import21 from 'ionic-angular/navigation/view-controller';
import * as import22 from 'ionic-angular/components/app/app';
import * as import23 from 'ionic-angular/components/toolbar/toolbar';
import * as import24 from 'ionic-angular/util/keyboard';
import * as import25 from '@angular/core/src/zone/ng_zone';
import * as import26 from 'ionic-angular/components/tabs/tabs';
import * as import27 from 'ionic-angular/components/toolbar/toolbar-title';
import * as import28 from 'ionic-angular/components/navbar/navbar';
import * as import29 from 'ionic-angular/components/card/card';
import * as import30 from 'ionic-angular/components/button/button';
import * as import31 from 'ionic-angular/components/grid/grid';
import * as import32 from 'ionic-angular/components/content/content';
export class Wrapper_ConfirmationPage {
  context:import0.ConfirmationPage;
  changed:boolean;
  constructor(p0:any,p1:any) {
    this.changed = false;
    this.context = new import0.ConfirmationPage(p0,p1);
  }
  detectChangesInternal(view:import1.AppView<any>,el:any,throwOnChange:boolean):boolean {
    var changed:any = this.changed;
    this.changed = false;
    return changed;
  }
}
var renderType_ConfirmationPage_Host:import2.RenderComponentType = (null as any);
class _View_ConfirmationPage_Host0 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import3.AppElement;
  _ConfirmationPage_0_4:Wrapper_ConfirmationPage;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement) {
    super(_View_ConfirmationPage_Host0,renderType_ConfirmationPage_Host,import6.ViewType.HOST,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    this._el_0 = this.selectOrCreateHostElement('page-confirmation',rootSelector,(null as any));
    this._appEl_0 = new import3.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_ConfirmationPage0(this.viewUtils,this.injector(0),this._appEl_0);
    this._ConfirmationPage_0_4 = new Wrapper_ConfirmationPage(this.parentInjector.get(import8.NavController),this.parentInjector.get(import9.AlertController));
    this._appEl_0.initComponent(this._ConfirmationPage_0_4.context,([] as any[]),compView_0);
    compView_0.create(this._ConfirmationPage_0_4.context,this.projectableNodes,(null as any));
    this.init(([] as any[]).concat([this._el_0]),[this._el_0],([] as any[]),([] as any[]));
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import0.ConfirmationPage) && (0 === requestNodeIndex))) { return this._ConfirmationPage_0_4.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._ConfirmationPage_0_4.detectChangesInternal(this,this._el_0,throwOnChange);
    this.detectContentChildrenChanges(throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_ConfirmationPage_Host0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement):import1.AppView<any> {
  if ((renderType_ConfirmationPage_Host === (null as any))) { (renderType_ConfirmationPage_Host = viewUtils.createRenderComponentType('',0,import10.ViewEncapsulation.None,([] as any[]),{})); }
  return new _View_ConfirmationPage_Host0(viewUtils,parentInjector,declarationEl);
}
export const ConfirmationPageNgFactory:import11.ComponentFactory<import0.ConfirmationPage> = new import11.ComponentFactory<import0.ConfirmationPage>('page-confirmation',viewFactory_ConfirmationPage_Host0,import0.ConfirmationPage);
const styles_ConfirmationPage:any[] = ([] as any[]);
var renderType_ConfirmationPage:import2.RenderComponentType = (null as any);
class _View_ConfirmationPage0 extends import1.AppView<import0.ConfirmationPage> {
  _el_0:any;
  _Header_0_3:import12.Wrapper_Header;
  _text_1:any;
  _el_2:any;
  /*private*/ _appEl_2:import3.AppElement;
  _Navbar_2_4:import13.Wrapper_Navbar;
  _text_3:any;
  _el_4:any;
  /*private*/ _appEl_4:import3.AppElement;
  _ToolbarTitle_4_4:import14.Wrapper_ToolbarTitle;
  _text_5:any;
  _text_6:any;
  _text_7:any;
  _text_8:any;
  _el_9:any;
  /*private*/ _appEl_9:import3.AppElement;
  _Content_9_4:import15.Wrapper_Content;
  _text_10:any;
  _el_11:any;
  _Grid_11_3:import16.Wrapper_Grid;
  _text_12:any;
  _el_13:any;
  _Row_13_3:import16.Wrapper_Row;
  _text_14:any;
  _el_15:any;
  _Col_15_3:import16.Wrapper_Col;
  _text_16:any;
  _el_17:any;
  _text_18:any;
  _el_19:any;
  _Card_19_3:import17.Wrapper_Card;
  _text_20:any;
  _el_21:any;
  _CardHeader_21_3:import17.Wrapper_CardHeader;
  _text_22:any;
  _text_23:any;
  _el_24:any;
  _CardContent_24_3:import17.Wrapper_CardContent;
  _text_25:any;
  _el_26:any;
  _Card_26_3:import17.Wrapper_Card;
  _text_27:any;
  _el_28:any;
  _text_29:any;
  _text_30:any;
  _el_31:any;
  _Grid_31_3:import16.Wrapper_Grid;
  _text_32:any;
  _el_33:any;
  _text_34:any;
  _text_35:any;
  _el_36:any;
  _Row_36_3:import16.Wrapper_Row;
  _text_37:any;
  _el_38:any;
  _Col_38_3:import16.Wrapper_Col;
  _text_39:any;
  _el_40:any;
  /*private*/ _appEl_40:import3.AppElement;
  _Button_40_4:import18.Wrapper_Button;
  _text_41:any;
  _text_42:any;
  _text_43:any;
  _el_44:any;
  _Col_44_3:import16.Wrapper_Col;
  _text_45:any;
  _el_46:any;
  /*private*/ _appEl_46:import3.AppElement;
  _Button_46_4:import18.Wrapper_Button;
  _text_47:any;
  _text_48:any;
  _text_49:any;
  _text_50:any;
  _text_51:any;
  _text_52:any;
  _text_53:any;
  _el_54:any;
  _text_55:any;
  _text_56:any;
  _text_57:any;
  _text_58:any;
  _text_59:any;
  /*private*/ _expr_1:any;
  /*private*/ _expr_2:any;
  /*private*/ _expr_3:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement) {
    super(_View_ConfirmationPage0,renderType_ConfirmationPage,import6.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._el_0 = this.renderer.createElement(parentRenderNode,'ion-header',(null as any));
    this._Header_0_3 = new import12.Wrapper_Header(this.parentInjector.get(import19.Config),new import20.ElementRef(this._el_0),this.renderer,this.parentInjector.get(import21.ViewController,(null as any)));
    this._text_1 = this.renderer.createText(this._el_0,'\n  ',(null as any));
    this._el_2 = this.renderer.createElement(this._el_0,'ion-navbar',(null as any));
    this.renderer.setElementAttribute(this._el_2,'class','toolbar');
    this.renderer.setElementAttribute(this._el_2,'color','lens-dark');
    this._appEl_2 = new import3.AppElement(2,0,this,this._el_2);
    var compView_2:any = import13.viewFactory_Navbar0(this.viewUtils,this.injector(2),this._appEl_2);
    this._Navbar_2_4 = new import13.Wrapper_Navbar(this.parentInjector.get(import22.App),this.parentInjector.get(import21.ViewController,(null as any)),this.parentInjector.get(import8.NavController,(null as any)),this.parentInjector.get(import19.Config),new import20.ElementRef(this._el_2),this.renderer);
    this._appEl_2.initComponent(this._Navbar_2_4.context,([] as any[]),compView_2);
    this._text_3 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._el_4 = this.renderer.createElement((null as any),'ion-title',(null as any));
    this.renderer.setElementAttribute(this._el_4,'text-center','');
    this._appEl_4 = new import3.AppElement(4,2,this,this._el_4);
    var compView_4:any = import14.viewFactory_ToolbarTitle0(this.viewUtils,this.injector(4),this._appEl_4);
    this._ToolbarTitle_4_4 = new import14.Wrapper_ToolbarTitle(this.parentInjector.get(import19.Config),new import20.ElementRef(this._el_4),this.renderer,this.parentInjector.get(import23.Toolbar,(null as any)),this._Navbar_2_4.context);
    this._appEl_4.initComponent(this._ToolbarTitle_4_4.context,([] as any[]),compView_4);
    this._text_5 = this.renderer.createText((null as any),'\n      iOptom\n    ',(null as any));
    compView_4.create(this._ToolbarTitle_4_4.context,[([] as any[]).concat([this._text_5])],(null as any));
    this._text_6 = this.renderer.createText((null as any),'\n  ',(null as any));
    compView_2.create(this._Navbar_2_4.context,[
      ([] as any[]),
      ([] as any[]),
      ([] as any[]),
      ([] as any[]).concat([
        this._text_3,
        this._el_4,
        this._text_6
      ]
      )
    ]
    ,(null as any));
    this._text_7 = this.renderer.createText(this._el_0,'\n',(null as any));
    this._text_8 = this.renderer.createText(parentRenderNode,'\n\n',(null as any));
    this._el_9 = this.renderer.createElement(parentRenderNode,'ion-content',(null as any));
    this.renderer.setElementAttribute(this._el_9,'text-center','');
    this._appEl_9 = new import3.AppElement(9,(null as any),this,this._el_9);
    var compView_9:any = import15.viewFactory_Content0(this.viewUtils,this.injector(9),this._appEl_9);
    this._Content_9_4 = new import15.Wrapper_Content(this.parentInjector.get(import19.Config),new import20.ElementRef(this._el_9),this.renderer,this.parentInjector.get(import22.App),this.parentInjector.get(import24.Keyboard),this.parentInjector.get(import25.NgZone),this.parentInjector.get(import21.ViewController,(null as any)),this.parentInjector.get(import26.Tabs,(null as any)));
    this._appEl_9.initComponent(this._Content_9_4.context,([] as any[]),compView_9);
    this._text_10 = this.renderer.createText((null as any),'\n\n  ',(null as any));
    this._el_11 = this.renderer.createElement((null as any),'ion-grid',(null as any));
    this.renderer.setElementAttribute(this._el_11,'style','height: 100%');
    this._Grid_11_3 = new import16.Wrapper_Grid();
    this._text_12 = this.renderer.createText(this._el_11,'\n    ',(null as any));
    this._el_13 = this.renderer.createElement(this._el_11,'ion-row',(null as any));
    this.renderer.setElementAttribute(this._el_13,'center','');
    this.renderer.setElementAttribute(this._el_13,'class','buttons-vertical');
    this._Row_13_3 = new import16.Wrapper_Row();
    this._text_14 = this.renderer.createText(this._el_13,'\n      ',(null as any));
    this._el_15 = this.renderer.createElement(this._el_13,'ion-col',(null as any));
    this._Col_15_3 = new import16.Wrapper_Col();
    this._text_16 = this.renderer.createText(this._el_15,'\n        ',(null as any));
    this._el_17 = this.renderer.createElement(this._el_15,'hr',(null as any));
    this._text_18 = this.renderer.createText(this._el_15,'\n        ',(null as any));
    this._el_19 = this.renderer.createElement(this._el_15,'ion-card',(null as any));
    this.renderer.setElementAttribute(this._el_19,'color','lens-dark');
    this._Card_19_3 = new import17.Wrapper_Card(this.parentInjector.get(import19.Config),new import20.ElementRef(this._el_19),this.renderer);
    this._text_20 = this.renderer.createText(this._el_19,'\n          ',(null as any));
    this._el_21 = this.renderer.createElement(this._el_19,'ion-card-header',(null as any));
    this.renderer.setElementAttribute(this._el_21,'color','lens-light');
    this._CardHeader_21_3 = new import17.Wrapper_CardHeader(this.parentInjector.get(import19.Config),new import20.ElementRef(this._el_21),this.renderer);
    this._text_22 = this.renderer.createText(this._el_21,'\n            Clarity 1 day Sphere\n          ',(null as any));
    this._text_23 = this.renderer.createText(this._el_19,'\n          ',(null as any));
    this._el_24 = this.renderer.createElement(this._el_19,'ion-card-content',(null as any));
    this._CardContent_24_3 = new import17.Wrapper_CardContent(this.parentInjector.get(import19.Config),new import20.ElementRef(this._el_24),this.renderer);
    this._text_25 = this.renderer.createText(this._el_24,'\n            ',(null as any));
    this._el_26 = this.renderer.createElement(this._el_24,'ion-card',(null as any));
    this._Card_26_3 = new import17.Wrapper_Card(this.parentInjector.get(import19.Config),new import20.ElementRef(this._el_26),this.renderer);
    this._text_27 = this.renderer.createText(this._el_26,'\n              ',(null as any));
    this._el_28 = this.renderer.createElement(this._el_26,'img',(null as any));
    this.renderer.setElementAttribute(this._el_28,'src','assets/images/wtf.png');
    this._text_29 = this.renderer.createText(this._el_26,'\n            ',(null as any));
    this._text_30 = this.renderer.createText(this._el_24,'\n            ',(null as any));
    this._el_31 = this.renderer.createElement(this._el_24,'ion-grid',(null as any));
    this._Grid_31_3 = new import16.Wrapper_Grid();
    this._text_32 = this.renderer.createText(this._el_31,'\n              ',(null as any));
    this._el_33 = this.renderer.createElement(this._el_31,'h3',(null as any));
    this._text_34 = this.renderer.createText(this._el_33,' Unusable buttons&input, to be continued/improved ',(null as any));
    this._text_35 = this.renderer.createText(this._el_31,'\n              ',(null as any));
    this._el_36 = this.renderer.createElement(this._el_31,'ion-row',(null as any));
    this._Row_36_3 = new import16.Wrapper_Row();
    this._text_37 = this.renderer.createText(this._el_36,'\n                ',(null as any));
    this._el_38 = this.renderer.createElement(this._el_36,'ion-col',(null as any));
    this._Col_38_3 = new import16.Wrapper_Col();
    this._text_39 = this.renderer.createText(this._el_38,'\n                  ',(null as any));
    this._el_40 = this.renderer.createElement(this._el_38,'button',(null as any));
    this.renderer.setElementAttribute(this._el_40,'color','lens-light');
    this.renderer.setElementAttribute(this._el_40,'ion-button','');
    this.renderer.setElementAttribute(this._el_40,'small','');
    this._appEl_40 = new import3.AppElement(40,38,this,this._el_40);
    var compView_40:any = import18.viewFactory_Button0(this.viewUtils,this.injector(40),this._appEl_40);
    this._Button_40_4 = new import18.Wrapper_Button((null as any),'',this.parentInjector.get(import19.Config),new import20.ElementRef(this._el_40),this.renderer);
    this._appEl_40.initComponent(this._Button_40_4.context,([] as any[]),compView_40);
    this._text_41 = this.renderer.createText((null as any),'1 click trails',(null as any));
    compView_40.create(this._Button_40_4.context,[([] as any[]).concat([this._text_41])],(null as any));
    this._text_42 = this.renderer.createText(this._el_38,'\n                ',(null as any));
    this._text_43 = this.renderer.createText(this._el_36,'\n                ',(null as any));
    this._el_44 = this.renderer.createElement(this._el_36,'ion-col',(null as any));
    this._Col_44_3 = new import16.Wrapper_Col();
    this._text_45 = this.renderer.createText(this._el_44,'\n                  ',(null as any));
    this._el_46 = this.renderer.createElement(this._el_44,'button',(null as any));
    this.renderer.setElementAttribute(this._el_46,'color','lens-light');
    this.renderer.setElementAttribute(this._el_46,'ion-button','');
    this.renderer.setElementAttribute(this._el_46,'small','');
    this._appEl_46 = new import3.AppElement(46,44,this,this._el_46);
    var compView_46:any = import18.viewFactory_Button0(this.viewUtils,this.injector(46),this._appEl_46);
    this._Button_46_4 = new import18.Wrapper_Button((null as any),'',this.parentInjector.get(import19.Config),new import20.ElementRef(this._el_46),this.renderer);
    this._appEl_46.initComponent(this._Button_46_4.context,([] as any[]),compView_46);
    this._text_47 = this.renderer.createText((null as any),'1 click trails',(null as any));
    compView_46.create(this._Button_46_4.context,[([] as any[]).concat([this._text_47])],(null as any));
    this._text_48 = this.renderer.createText(this._el_44,'\n                ',(null as any));
    this._text_49 = this.renderer.createText(this._el_36,'\n              ',(null as any));
    this._text_50 = this.renderer.createText(this._el_31,'\n            ',(null as any));
    this._text_51 = this.renderer.createText(this._el_24,'\n          ',(null as any));
    this._text_52 = this.renderer.createText(this._el_19,'\n        ',(null as any));
    this._text_53 = this.renderer.createText(this._el_15,'\n        ',(null as any));
    this._el_54 = this.renderer.createElement(this._el_15,'hr',(null as any));
    this._text_55 = this.renderer.createText(this._el_15,'\n      ',(null as any));
    this._text_56 = this.renderer.createText(this._el_13,'\n    ',(null as any));
    this._text_57 = this.renderer.createText(this._el_11,'\n  ',(null as any));
    this._text_58 = this.renderer.createText((null as any),'\n',(null as any));
    compView_9.create(this._Content_9_4.context,[
      ([] as any[]),
      ([] as any[]).concat([
        this._text_10,
        this._el_11,
        this._text_58
      ]
      ),
      ([] as any[])
    ]
    ,(null as any));
    this._text_59 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this._expr_1 = import7.UNINITIALIZED;
    this._expr_2 = import7.UNINITIALIZED;
    this._expr_3 = import7.UNINITIALIZED;
    var disposable_0:Function = this.renderer.listen(this._el_40,'click',this.eventHandler(this._handle_click_40_0.bind(this)));
    var disposable_1:Function = this.renderer.listen(this._el_46,'click',this.eventHandler(this._handle_click_46_0.bind(this)));
    this.init(([] as any[]),[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._text_6,
      this._text_7,
      this._text_8,
      this._el_9,
      this._text_10,
      this._el_11,
      this._text_12,
      this._el_13,
      this._text_14,
      this._el_15,
      this._text_16,
      this._el_17,
      this._text_18,
      this._el_19,
      this._text_20,
      this._el_21,
      this._text_22,
      this._text_23,
      this._el_24,
      this._text_25,
      this._el_26,
      this._text_27,
      this._el_28,
      this._text_29,
      this._text_30,
      this._el_31,
      this._text_32,
      this._el_33,
      this._text_34,
      this._text_35,
      this._el_36,
      this._text_37,
      this._el_38,
      this._text_39,
      this._el_40,
      this._text_41,
      this._text_42,
      this._text_43,
      this._el_44,
      this._text_45,
      this._el_46,
      this._text_47,
      this._text_48,
      this._text_49,
      this._text_50,
      this._text_51,
      this._text_52,
      this._text_53,
      this._el_54,
      this._text_55,
      this._text_56,
      this._text_57,
      this._text_58,
      this._text_59
    ]
    ,[
      disposable_0,
      disposable_1
    ]
    ,([] as any[]));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import27.ToolbarTitle) && ((4 <= requestNodeIndex) && (requestNodeIndex <= 5)))) { return this._ToolbarTitle_4_4.context; }
    if (((token === import28.Navbar) && ((2 <= requestNodeIndex) && (requestNodeIndex <= 6)))) { return this._Navbar_2_4.context; }
    if (((token === import23.Header) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 7)))) { return this._Header_0_3.context; }
    if (((token === import29.CardHeader) && ((21 <= requestNodeIndex) && (requestNodeIndex <= 22)))) { return this._CardHeader_21_3.context; }
    if (((token === import29.Card) && ((26 <= requestNodeIndex) && (requestNodeIndex <= 29)))) { return this._Card_26_3.context; }
    if (((token === import30.Button) && ((40 <= requestNodeIndex) && (requestNodeIndex <= 41)))) { return this._Button_40_4.context; }
    if (((token === import31.Col) && ((38 <= requestNodeIndex) && (requestNodeIndex <= 42)))) { return this._Col_38_3.context; }
    if (((token === import30.Button) && ((46 <= requestNodeIndex) && (requestNodeIndex <= 47)))) { return this._Button_46_4.context; }
    if (((token === import31.Col) && ((44 <= requestNodeIndex) && (requestNodeIndex <= 48)))) { return this._Col_44_3.context; }
    if (((token === import31.Row) && ((36 <= requestNodeIndex) && (requestNodeIndex <= 49)))) { return this._Row_36_3.context; }
    if (((token === import31.Grid) && ((31 <= requestNodeIndex) && (requestNodeIndex <= 50)))) { return this._Grid_31_3.context; }
    if (((token === import29.CardContent) && ((24 <= requestNodeIndex) && (requestNodeIndex <= 51)))) { return this._CardContent_24_3.context; }
    if (((token === import29.Card) && ((19 <= requestNodeIndex) && (requestNodeIndex <= 52)))) { return this._Card_19_3.context; }
    if (((token === import31.Col) && ((15 <= requestNodeIndex) && (requestNodeIndex <= 55)))) { return this._Col_15_3.context; }
    if (((token === import31.Row) && ((13 <= requestNodeIndex) && (requestNodeIndex <= 56)))) { return this._Row_13_3.context; }
    if (((token === import31.Grid) && ((11 <= requestNodeIndex) && (requestNodeIndex <= 57)))) { return this._Grid_11_3.context; }
    if (((token === import32.Content) && ((9 <= requestNodeIndex) && (requestNodeIndex <= 58)))) { return this._Content_9_4.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._Header_0_3.detectChangesInternal(this,this._el_0,throwOnChange);
    const currVal_0:any = 'lens-dark';
    this._Navbar_2_4.check_color(currVal_0,throwOnChange,false);
    this._Navbar_2_4.detectChangesInternal(this,this._el_2,throwOnChange);
    if (this._ToolbarTitle_4_4.detectChangesInternal(this,this._el_4,throwOnChange)) { this._appEl_4.componentView.markAsCheckOnce(); }
    if (this._Content_9_4.detectChangesInternal(this,this._el_9,throwOnChange)) { this._appEl_9.componentView.markAsCheckOnce(); }
    this._Grid_11_3.detectChangesInternal(this,this._el_11,throwOnChange);
    this._Row_13_3.detectChangesInternal(this,this._el_13,throwOnChange);
    this._Col_15_3.detectChangesInternal(this,this._el_15,throwOnChange);
    const currVal_4:any = 'lens-dark';
    this._Card_19_3.check_color(currVal_4,throwOnChange,false);
    this._Card_19_3.detectChangesInternal(this,this._el_19,throwOnChange);
    const currVal_5:any = 'lens-light';
    this._CardHeader_21_3.check_color(currVal_5,throwOnChange,false);
    this._CardHeader_21_3.detectChangesInternal(this,this._el_21,throwOnChange);
    this._CardContent_24_3.detectChangesInternal(this,this._el_24,throwOnChange);
    this._Card_26_3.detectChangesInternal(this,this._el_26,throwOnChange);
    this._Grid_31_3.detectChangesInternal(this,this._el_31,throwOnChange);
    this._Row_36_3.detectChangesInternal(this,this._el_36,throwOnChange);
    this._Col_38_3.detectChangesInternal(this,this._el_38,throwOnChange);
    const currVal_7:any = '';
    this._Button_40_4.check_small(currVal_7,throwOnChange,false);
    const currVal_8:any = 'lens-light';
    this._Button_40_4.check_color(currVal_8,throwOnChange,false);
    if (this._Button_40_4.detectChangesInternal(this,this._el_40,throwOnChange)) { this._appEl_40.componentView.markAsCheckOnce(); }
    this._Col_44_3.detectChangesInternal(this,this._el_44,throwOnChange);
    const currVal_10:any = '';
    this._Button_46_4.check_small(currVal_10,throwOnChange,false);
    const currVal_11:any = 'lens-light';
    this._Button_46_4.check_color(currVal_11,throwOnChange,false);
    if (this._Button_46_4.detectChangesInternal(this,this._el_46,throwOnChange)) { this._appEl_46.componentView.markAsCheckOnce(); }
    this.detectContentChildrenChanges(throwOnChange);
    if (!throwOnChange) {
      if ((this.numberOfChecks === 0)) { this._Button_40_4.context.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Button_46_4.context.ngAfterContentInit(); }
    }
    const currVal_1:any = this._Navbar_2_4.context._hidden;
    if (import4.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this.renderer.setElementProperty(this._el_2,'hidden',currVal_1);
      this._expr_1 = currVal_1;
    }
    const currVal_2:any = this._Navbar_2_4.context._sbPadding;
    if (import4.checkBinding(throwOnChange,this._expr_2,currVal_2)) {
      this.renderer.setElementClass(this._el_2,'statusbar-padding',currVal_2);
      this._expr_2 = currVal_2;
    }
    const currVal_3:any = this._Content_9_4.context._sbPadding;
    if (import4.checkBinding(throwOnChange,this._expr_3,currVal_3)) {
      this.renderer.setElementClass(this._el_9,'statusbar-padding',currVal_3);
      this._expr_3 = currVal_3;
    }
    this.detectViewChildrenChanges(throwOnChange);
    if (!throwOnChange) { if ((this.numberOfChecks === 0)) { this._Navbar_2_4.context.ngAfterViewInit(); } }
  }
  destroyInternal():void {
    this._Content_9_4.context.ngOnDestroy();
  }
  private _handle_click_40_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.next()) !== false);
    return (true && pd_0);
  }
  private _handle_click_46_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.next()) !== false);
    return (true && pd_0);
  }
}
export function viewFactory_ConfirmationPage0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement):import1.AppView<import0.ConfirmationPage> {
  if ((renderType_ConfirmationPage === (null as any))) { (renderType_ConfirmationPage = viewUtils.createRenderComponentType('',0,import10.ViewEncapsulation.None,styles_ConfirmationPage,{})); }
  return new _View_ConfirmationPage0(viewUtils,parentInjector,declarationEl);
}