/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from './order-details';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/render/api';
import * as import3 from '@angular/core/src/linker/element';
import * as import4 from '@angular/core/src/linker/view_utils';
import * as import5 from '@angular/core/src/di/injector';
import * as import6 from '@angular/core/src/linker/view_type';
import * as import7 from '@angular/core/src/change_detection/change_detection';
import * as import8 from 'ionic-angular/navigation/nav-controller';
import * as import9 from '../../providers/lens-provider';
import * as import10 from '@angular/core/src/metadata/view';
import * as import11 from '@angular/core/src/linker/component_factory';
import * as import12 from '../../node_modules/ionic-angular/components/toolbar/toolbar.ngfactory';
import * as import13 from '../../node_modules/ionic-angular/components/navbar/navbar.ngfactory';
import * as import14 from '../../node_modules/ionic-angular/components/toolbar/toolbar-title.ngfactory';
import * as import15 from '../../node_modules/ionic-angular/components/content/content.ngfactory';
import * as import16 from '../../node_modules/ionic-angular/components/grid/grid.ngfactory';
import * as import17 from '../../node_modules/ionic-angular/components/list/list.ngfactory';
import * as import18 from '../../node_modules/ionic-angular/components/item/item.ngfactory';
import * as import19 from '../../node_modules/ionic-angular/components/list/list-header.ngfactory';
import * as import20 from '@angular/core/src/linker/query_list';
import * as import21 from '../../node_modules/ionic-angular/components/note/note.ngfactory';
import * as import22 from 'ionic-angular/config/config';
import * as import23 from '@angular/core/src/linker/element_ref';
import * as import24 from 'ionic-angular/navigation/view-controller';
import * as import25 from 'ionic-angular/components/app/app';
import * as import26 from 'ionic-angular/components/toolbar/toolbar';
import * as import27 from 'ionic-angular/util/keyboard';
import * as import28 from '@angular/core/src/zone/ng_zone';
import * as import29 from 'ionic-angular/components/tabs/tabs';
import * as import30 from 'ionic-angular/gestures/gesture-controller';
import * as import31 from 'ionic-angular/util/form';
import * as import32 from 'ionic-angular/components/item/item-reorder';
import * as import33 from 'ionic-angular/components/toolbar/toolbar-title';
import * as import34 from 'ionic-angular/components/navbar/navbar';
import * as import35 from 'ionic-angular/components/item/item';
import * as import36 from 'ionic-angular/components/list/list-header';
import * as import37 from 'ionic-angular/components/note/note';
import * as import38 from 'ionic-angular/components/list/list';
import * as import39 from 'ionic-angular/components/grid/grid';
import * as import40 from 'ionic-angular/components/content/content';
export class Wrapper_OrderDetailsPage {
  context:import0.OrderDetailsPage;
  changed:boolean;
  constructor(p0:any,p1:any) {
    this.changed = false;
    this.context = new import0.OrderDetailsPage(p0,p1);
  }
  detectChangesInternal(view:import1.AppView<any>,el:any,throwOnChange:boolean):boolean {
    var changed:any = this.changed;
    this.changed = false;
    return changed;
  }
}
var renderType_OrderDetailsPage_Host:import2.RenderComponentType = (null as any);
class _View_OrderDetailsPage_Host0 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import3.AppElement;
  _OrderDetailsPage_0_4:Wrapper_OrderDetailsPage;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement) {
    super(_View_OrderDetailsPage_Host0,renderType_OrderDetailsPage_Host,import6.ViewType.HOST,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    this._el_0 = this.selectOrCreateHostElement('page-order-details',rootSelector,(null as any));
    this._appEl_0 = new import3.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_OrderDetailsPage0(this.viewUtils,this.injector(0),this._appEl_0);
    this._OrderDetailsPage_0_4 = new Wrapper_OrderDetailsPage(this.parentInjector.get(import8.NavController),this.parentInjector.get(import9.LensProvider));
    this._appEl_0.initComponent(this._OrderDetailsPage_0_4.context,([] as any[]),compView_0);
    compView_0.create(this._OrderDetailsPage_0_4.context,this.projectableNodes,(null as any));
    this.init(([] as any[]).concat([this._el_0]),[this._el_0],([] as any[]),([] as any[]));
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import0.OrderDetailsPage) && (0 === requestNodeIndex))) { return this._OrderDetailsPage_0_4.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._OrderDetailsPage_0_4.detectChangesInternal(this,this._el_0,throwOnChange);
    this.detectContentChildrenChanges(throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_OrderDetailsPage_Host0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement):import1.AppView<any> {
  if ((renderType_OrderDetailsPage_Host === (null as any))) { (renderType_OrderDetailsPage_Host = viewUtils.createRenderComponentType('',0,import10.ViewEncapsulation.None,([] as any[]),{})); }
  return new _View_OrderDetailsPage_Host0(viewUtils,parentInjector,declarationEl);
}
export const OrderDetailsPageNgFactory:import11.ComponentFactory<import0.OrderDetailsPage> = new import11.ComponentFactory<import0.OrderDetailsPage>('page-order-details',viewFactory_OrderDetailsPage_Host0,import0.OrderDetailsPage);
const styles_OrderDetailsPage:any[] = ([] as any[]);
var renderType_OrderDetailsPage:import2.RenderComponentType = (null as any);
class _View_OrderDetailsPage0 extends import1.AppView<import0.OrderDetailsPage> {
  _el_0:any;
  _Header_0_3:import12.Wrapper_Header;
  _text_1:any;
  _el_2:any;
  /*private*/ _appEl_2:import3.AppElement;
  _Navbar_2_4:import13.Wrapper_Navbar;
  _text_3:any;
  _el_4:any;
  /*private*/ _appEl_4:import3.AppElement;
  _ToolbarTitle_4_4:import14.Wrapper_ToolbarTitle;
  _text_5:any;
  _text_6:any;
  _text_7:any;
  _text_8:any;
  _el_9:any;
  /*private*/ _appEl_9:import3.AppElement;
  _Content_9_4:import15.Wrapper_Content;
  _text_10:any;
  _el_11:any;
  _Grid_11_3:import16.Wrapper_Grid;
  _text_12:any;
  _el_13:any;
  _Row_13_3:import16.Wrapper_Row;
  _text_14:any;
  _el_15:any;
  _Col_15_3:import16.Wrapper_Col;
  _text_16:any;
  _el_17:any;
  _List_17_3:import17.Wrapper_List;
  _text_18:any;
  _el_19:any;
  /*private*/ _appEl_19:import3.AppElement;
  _Item_19_4:import18.Wrapper_Item;
  _ListHeader_19_5:import19.Wrapper_ListHeader;
  _query_Label_19_0:import20.QueryList<any>;
  _query_Button_19_1:import20.QueryList<any>;
  _query_Icon_19_2:import20.QueryList<any>;
  _text_20:any;
  _text_21:any;
  _el_22:any;
  /*private*/ _appEl_22:import3.AppElement;
  _Item_22_4:import18.Wrapper_Item;
  _ItemContent_22_5:import18.Wrapper_ItemContent;
  _query_Label_22_0:import20.QueryList<any>;
  _query_Button_22_1:import20.QueryList<any>;
  _query_Icon_22_2:import20.QueryList<any>;
  _text_23:any;
  _el_24:any;
  _Note_24_3:import21.Wrapper_Note;
  _text_25:any;
  _text_26:any;
  _text_27:any;
  _el_28:any;
  /*private*/ _appEl_28:import3.AppElement;
  _Item_28_4:import18.Wrapper_Item;
  _ItemContent_28_5:import18.Wrapper_ItemContent;
  _query_Label_28_0:import20.QueryList<any>;
  _query_Button_28_1:import20.QueryList<any>;
  _query_Icon_28_2:import20.QueryList<any>;
  _text_29:any;
  _el_30:any;
  _Note_30_3:import21.Wrapper_Note;
  _text_31:any;
  _text_32:any;
  _text_33:any;
  _el_34:any;
  /*private*/ _appEl_34:import3.AppElement;
  _Item_34_4:import18.Wrapper_Item;
  _ItemContent_34_5:import18.Wrapper_ItemContent;
  _query_Label_34_0:import20.QueryList<any>;
  _query_Button_34_1:import20.QueryList<any>;
  _query_Icon_34_2:import20.QueryList<any>;
  _text_35:any;
  _el_36:any;
  _Note_36_3:import21.Wrapper_Note;
  _text_37:any;
  _text_38:any;
  _text_39:any;
  _el_40:any;
  /*private*/ _appEl_40:import3.AppElement;
  _Item_40_4:import18.Wrapper_Item;
  _ItemContent_40_5:import18.Wrapper_ItemContent;
  _query_Label_40_0:import20.QueryList<any>;
  _query_Button_40_1:import20.QueryList<any>;
  _query_Icon_40_2:import20.QueryList<any>;
  _text_41:any;
  _el_42:any;
  _Note_42_3:import21.Wrapper_Note;
  _text_43:any;
  _text_44:any;
  _text_45:any;
  _el_46:any;
  /*private*/ _appEl_46:import3.AppElement;
  _Item_46_4:import18.Wrapper_Item;
  _ItemContent_46_5:import18.Wrapper_ItemContent;
  _query_Label_46_0:import20.QueryList<any>;
  _query_Button_46_1:import20.QueryList<any>;
  _query_Icon_46_2:import20.QueryList<any>;
  _text_47:any;
  _el_48:any;
  _Note_48_3:import21.Wrapper_Note;
  _text_49:any;
  _text_50:any;
  _text_51:any;
  _el_52:any;
  /*private*/ _appEl_52:import3.AppElement;
  _Item_52_4:import18.Wrapper_Item;
  _ItemContent_52_5:import18.Wrapper_ItemContent;
  _query_Label_52_0:import20.QueryList<any>;
  _query_Button_52_1:import20.QueryList<any>;
  _query_Icon_52_2:import20.QueryList<any>;
  _text_53:any;
  _el_54:any;
  _Note_54_3:import21.Wrapper_Note;
  _text_55:any;
  _text_56:any;
  _text_57:any;
  _el_58:any;
  /*private*/ _appEl_58:import3.AppElement;
  _Item_58_4:import18.Wrapper_Item;
  _ItemContent_58_5:import18.Wrapper_ItemContent;
  _query_Label_58_0:import20.QueryList<any>;
  _query_Button_58_1:import20.QueryList<any>;
  _query_Icon_58_2:import20.QueryList<any>;
  _text_59:any;
  _el_60:any;
  _Note_60_3:import21.Wrapper_Note;
  _text_61:any;
  _text_62:any;
  _text_63:any;
  _text_64:any;
  _text_65:any;
  _text_66:any;
  _text_67:any;
  _text_68:any;
  /*private*/ _expr_1:any;
  /*private*/ _expr_2:any;
  /*private*/ _expr_3:any;
  /*private*/ _expr_4:any;
  /*private*/ _expr_5:any;
  /*private*/ _expr_6:any;
  /*private*/ _expr_7:any;
  /*private*/ _expr_8:any;
  /*private*/ _expr_9:any;
  /*private*/ _expr_10:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement) {
    super(_View_OrderDetailsPage0,renderType_OrderDetailsPage,import6.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._el_0 = this.renderer.createElement(parentRenderNode,'ion-header',(null as any));
    this._Header_0_3 = new import12.Wrapper_Header(this.parentInjector.get(import22.Config),new import23.ElementRef(this._el_0),this.renderer,this.parentInjector.get(import24.ViewController,(null as any)));
    this._text_1 = this.renderer.createText(this._el_0,'\n  ',(null as any));
    this._el_2 = this.renderer.createElement(this._el_0,'ion-navbar',(null as any));
    this.renderer.setElementAttribute(this._el_2,'class','toolbar');
    this.renderer.setElementAttribute(this._el_2,'color','lens-dark');
    this._appEl_2 = new import3.AppElement(2,0,this,this._el_2);
    var compView_2:any = import13.viewFactory_Navbar0(this.viewUtils,this.injector(2),this._appEl_2);
    this._Navbar_2_4 = new import13.Wrapper_Navbar(this.parentInjector.get(import25.App),this.parentInjector.get(import24.ViewController,(null as any)),this.parentInjector.get(import8.NavController,(null as any)),this.parentInjector.get(import22.Config),new import23.ElementRef(this._el_2),this.renderer);
    this._appEl_2.initComponent(this._Navbar_2_4.context,([] as any[]),compView_2);
    this._text_3 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._el_4 = this.renderer.createElement((null as any),'ion-title',(null as any));
    this.renderer.setElementAttribute(this._el_4,'text-center','');
    this._appEl_4 = new import3.AppElement(4,2,this,this._el_4);
    var compView_4:any = import14.viewFactory_ToolbarTitle0(this.viewUtils,this.injector(4),this._appEl_4);
    this._ToolbarTitle_4_4 = new import14.Wrapper_ToolbarTitle(this.parentInjector.get(import22.Config),new import23.ElementRef(this._el_4),this.renderer,this.parentInjector.get(import26.Toolbar,(null as any)),this._Navbar_2_4.context);
    this._appEl_4.initComponent(this._ToolbarTitle_4_4.context,([] as any[]),compView_4);
    this._text_5 = this.renderer.createText((null as any),'\n      iOptom\n    ',(null as any));
    compView_4.create(this._ToolbarTitle_4_4.context,[([] as any[]).concat([this._text_5])],(null as any));
    this._text_6 = this.renderer.createText((null as any),'\n  ',(null as any));
    compView_2.create(this._Navbar_2_4.context,[
      ([] as any[]),
      ([] as any[]),
      ([] as any[]),
      ([] as any[]).concat([
        this._text_3,
        this._el_4,
        this._text_6
      ]
      )
    ]
    ,(null as any));
    this._text_7 = this.renderer.createText(this._el_0,'\n',(null as any));
    this._text_8 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this._el_9 = this.renderer.createElement(parentRenderNode,'ion-content',(null as any));
    this._appEl_9 = new import3.AppElement(9,(null as any),this,this._el_9);
    var compView_9:any = import15.viewFactory_Content0(this.viewUtils,this.injector(9),this._appEl_9);
    this._Content_9_4 = new import15.Wrapper_Content(this.parentInjector.get(import22.Config),new import23.ElementRef(this._el_9),this.renderer,this.parentInjector.get(import25.App),this.parentInjector.get(import27.Keyboard),this.parentInjector.get(import28.NgZone),this.parentInjector.get(import24.ViewController,(null as any)),this.parentInjector.get(import29.Tabs,(null as any)));
    this._appEl_9.initComponent(this._Content_9_4.context,([] as any[]),compView_9);
    this._text_10 = this.renderer.createText((null as any),'\n  ',(null as any));
    this._el_11 = this.renderer.createElement((null as any),'ion-grid',(null as any));
    this.renderer.setElementAttribute(this._el_11,'style','height: 100%');
    this._Grid_11_3 = new import16.Wrapper_Grid();
    this._text_12 = this.renderer.createText(this._el_11,'\n    ',(null as any));
    this._el_13 = this.renderer.createElement(this._el_11,'ion-row',(null as any));
    this.renderer.setElementAttribute(this._el_13,'center','');
    this.renderer.setElementAttribute(this._el_13,'class','buttons-vertical');
    this._Row_13_3 = new import16.Wrapper_Row();
    this._text_14 = this.renderer.createText(this._el_13,'\n      ',(null as any));
    this._el_15 = this.renderer.createElement(this._el_13,'ion-col',(null as any));
    this.renderer.setElementAttribute(this._el_15,'offset-10','');
    this.renderer.setElementAttribute(this._el_15,'width-80','');
    this._Col_15_3 = new import16.Wrapper_Col();
    this._text_16 = this.renderer.createText(this._el_15,'\n        ',(null as any));
    this._el_17 = this.renderer.createElement(this._el_15,'ion-list',(null as any));
    this._List_17_3 = new import17.Wrapper_List(this.parentInjector.get(import22.Config),new import23.ElementRef(this._el_17),this.renderer,this.parentInjector.get(import30.GestureController));
    this._text_18 = this.renderer.createText(this._el_17,'\n          ',(null as any));
    this._el_19 = this.renderer.createElement(this._el_17,'ion-list-header',(null as any));
    this.renderer.setElementAttribute(this._el_19,'class','item');
    this._appEl_19 = new import3.AppElement(19,17,this,this._el_19);
    var compView_19:any = import18.viewFactory_Item0(this.viewUtils,this.injector(19),this._appEl_19);
    this._Item_19_4 = new import18.Wrapper_Item(this.parentInjector.get(import31.Form),this.parentInjector.get(import22.Config),new import23.ElementRef(this._el_19),this.renderer,this.parentInjector.get(import32.ItemReorder,(null as any)));
    this._ListHeader_19_5 = new import19.Wrapper_ListHeader(this.parentInjector.get(import22.Config),this.renderer,new import23.ElementRef(this._el_19),(null as any));
    this._query_Label_19_0 = new import20.QueryList<any>();
    this._query_Button_19_1 = new import20.QueryList<any>();
    this._query_Icon_19_2 = new import20.QueryList<any>();
    this._appEl_19.initComponent(this._Item_19_4.context,([] as any[]),compView_19);
    this._text_20 = this.renderer.createText((null as any),'Order Details(to be sent)',(null as any));
    this._query_Label_19_0.reset(([] as any[]));
    this._Item_19_4.context.contentLabel = this._query_Label_19_0.first;
    compView_19.create(this._Item_19_4.context,[
      ([] as any[]),
      ([] as any[]),
      ([] as any[]).concat([this._text_20]),
      ([] as any[]),
      ([] as any[])
    ]
    ,(null as any));
    this._text_21 = this.renderer.createText(this._el_17,'\n          ',(null as any));
    this._el_22 = this.renderer.createElement(this._el_17,'ion-item',(null as any));
    this.renderer.setElementAttribute(this._el_22,'class','item item-block');
    this._appEl_22 = new import3.AppElement(22,17,this,this._el_22);
    var compView_22:any = import18.viewFactory_Item0(this.viewUtils,this.injector(22),this._appEl_22);
    this._Item_22_4 = new import18.Wrapper_Item(this.parentInjector.get(import31.Form),this.parentInjector.get(import22.Config),new import23.ElementRef(this._el_22),this.renderer,this.parentInjector.get(import32.ItemReorder,(null as any)));
    this._ItemContent_22_5 = new import18.Wrapper_ItemContent();
    this._query_Label_22_0 = new import20.QueryList<any>();
    this._query_Button_22_1 = new import20.QueryList<any>();
    this._query_Icon_22_2 = new import20.QueryList<any>();
    this._appEl_22.initComponent(this._Item_22_4.context,([] as any[]),compView_22);
    this._text_23 = this.renderer.createText((null as any),'\n            Order name ',(null as any));
    this._el_24 = this.renderer.createElement((null as any),'ion-note',(null as any));
    this.renderer.setElementAttribute(this._el_24,'item-right','');
    this._Note_24_3 = new import21.Wrapper_Note();
    this._text_25 = this.renderer.createText(this._el_24,'',(null as any));
    this._text_26 = this.renderer.createText((null as any),'\n          ',(null as any));
    this._query_Label_22_0.reset(([] as any[]));
    this._Item_22_4.context.contentLabel = this._query_Label_22_0.first;
    compView_22.create(this._Item_22_4.context,[
      ([] as any[]),
      ([] as any[]),
      ([] as any[]).concat([
        this._text_23,
        this._text_26
      ]
      ),
      ([] as any[]),
      ([] as any[]).concat([this._el_24])
    ]
    ,(null as any));
    this._text_27 = this.renderer.createText(this._el_17,'\n          ',(null as any));
    this._el_28 = this.renderer.createElement(this._el_17,'ion-item',(null as any));
    this.renderer.setElementAttribute(this._el_28,'class','item item-block');
    this._appEl_28 = new import3.AppElement(28,17,this,this._el_28);
    var compView_28:any = import18.viewFactory_Item0(this.viewUtils,this.injector(28),this._appEl_28);
    this._Item_28_4 = new import18.Wrapper_Item(this.parentInjector.get(import31.Form),this.parentInjector.get(import22.Config),new import23.ElementRef(this._el_28),this.renderer,this.parentInjector.get(import32.ItemReorder,(null as any)));
    this._ItemContent_28_5 = new import18.Wrapper_ItemContent();
    this._query_Label_28_0 = new import20.QueryList<any>();
    this._query_Button_28_1 = new import20.QueryList<any>();
    this._query_Icon_28_2 = new import20.QueryList<any>();
    this._appEl_28.initComponent(this._Item_28_4.context,([] as any[]),compView_28);
    this._text_29 = this.renderer.createText((null as any),'\n            Lens type ',(null as any));
    this._el_30 = this.renderer.createElement((null as any),'ion-note',(null as any));
    this.renderer.setElementAttribute(this._el_30,'item-right','');
    this._Note_30_3 = new import21.Wrapper_Note();
    this._text_31 = this.renderer.createText(this._el_30,'',(null as any));
    this._text_32 = this.renderer.createText((null as any),'\n          ',(null as any));
    this._query_Label_28_0.reset(([] as any[]));
    this._Item_28_4.context.contentLabel = this._query_Label_28_0.first;
    compView_28.create(this._Item_28_4.context,[
      ([] as any[]),
      ([] as any[]),
      ([] as any[]).concat([
        this._text_29,
        this._text_32
      ]
      ),
      ([] as any[]),
      ([] as any[]).concat([this._el_30])
    ]
    ,(null as any));
    this._text_33 = this.renderer.createText(this._el_17,'\n          ',(null as any));
    this._el_34 = this.renderer.createElement(this._el_17,'ion-item',(null as any));
    this.renderer.setElementAttribute(this._el_34,'class','item item-block');
    this._appEl_34 = new import3.AppElement(34,17,this,this._el_34);
    var compView_34:any = import18.viewFactory_Item0(this.viewUtils,this.injector(34),this._appEl_34);
    this._Item_34_4 = new import18.Wrapper_Item(this.parentInjector.get(import31.Form),this.parentInjector.get(import22.Config),new import23.ElementRef(this._el_34),this.renderer,this.parentInjector.get(import32.ItemReorder,(null as any)));
    this._ItemContent_34_5 = new import18.Wrapper_ItemContent();
    this._query_Label_34_0 = new import20.QueryList<any>();
    this._query_Button_34_1 = new import20.QueryList<any>();
    this._query_Icon_34_2 = new import20.QueryList<any>();
    this._appEl_34.initComponent(this._Item_34_4.context,([] as any[]),compView_34);
    this._text_35 = this.renderer.createText((null as any),'\n            Lens modality ',(null as any));
    this._el_36 = this.renderer.createElement((null as any),'ion-note',(null as any));
    this.renderer.setElementAttribute(this._el_36,'item-right','');
    this._Note_36_3 = new import21.Wrapper_Note();
    this._text_37 = this.renderer.createText(this._el_36,'',(null as any));
    this._text_38 = this.renderer.createText((null as any),'\n          ',(null as any));
    this._query_Label_34_0.reset(([] as any[]));
    this._Item_34_4.context.contentLabel = this._query_Label_34_0.first;
    compView_34.create(this._Item_34_4.context,[
      ([] as any[]),
      ([] as any[]),
      ([] as any[]).concat([
        this._text_35,
        this._text_38
      ]
      ),
      ([] as any[]),
      ([] as any[]).concat([this._el_36])
    ]
    ,(null as any));
    this._text_39 = this.renderer.createText(this._el_17,'\n          ',(null as any));
    this._el_40 = this.renderer.createElement(this._el_17,'ion-item',(null as any));
    this.renderer.setElementAttribute(this._el_40,'class','item item-block');
    this._appEl_40 = new import3.AppElement(40,17,this,this._el_40);
    var compView_40:any = import18.viewFactory_Item0(this.viewUtils,this.injector(40),this._appEl_40);
    this._Item_40_4 = new import18.Wrapper_Item(this.parentInjector.get(import31.Form),this.parentInjector.get(import22.Config),new import23.ElementRef(this._el_40),this.renderer,this.parentInjector.get(import32.ItemReorder,(null as any)));
    this._ItemContent_40_5 = new import18.Wrapper_ItemContent();
    this._query_Label_40_0 = new import20.QueryList<any>();
    this._query_Button_40_1 = new import20.QueryList<any>();
    this._query_Icon_40_2 = new import20.QueryList<any>();
    this._appEl_40.initComponent(this._Item_40_4.context,([] as any[]),compView_40);
    this._text_41 = this.renderer.createText((null as any),'\n            Was RX adjusted? ',(null as any));
    this._el_42 = this.renderer.createElement((null as any),'ion-note',(null as any));
    this.renderer.setElementAttribute(this._el_42,'item-right','');
    this._Note_42_3 = new import21.Wrapper_Note();
    this._text_43 = this.renderer.createText(this._el_42,'',(null as any));
    this._text_44 = this.renderer.createText((null as any),'\n          ',(null as any));
    this._query_Label_40_0.reset(([] as any[]));
    this._Item_40_4.context.contentLabel = this._query_Label_40_0.first;
    compView_40.create(this._Item_40_4.context,[
      ([] as any[]),
      ([] as any[]),
      ([] as any[]).concat([
        this._text_41,
        this._text_44
      ]
      ),
      ([] as any[]),
      ([] as any[]).concat([this._el_42])
    ]
    ,(null as any));
    this._text_45 = this.renderer.createText(this._el_17,'\n          ',(null as any));
    this._el_46 = this.renderer.createElement(this._el_17,'ion-item',(null as any));
    this.renderer.setElementAttribute(this._el_46,'class','item item-block');
    this._appEl_46 = new import3.AppElement(46,17,this,this._el_46);
    var compView_46:any = import18.viewFactory_Item0(this.viewUtils,this.injector(46),this._appEl_46);
    this._Item_46_4 = new import18.Wrapper_Item(this.parentInjector.get(import31.Form),this.parentInjector.get(import22.Config),new import23.ElementRef(this._el_46),this.renderer,this.parentInjector.get(import32.ItemReorder,(null as any)));
    this._ItemContent_46_5 = new import18.Wrapper_ItemContent();
    this._query_Label_46_0 = new import20.QueryList<any>();
    this._query_Button_46_1 = new import20.QueryList<any>();
    this._query_Icon_46_2 = new import20.QueryList<any>();
    this._appEl_46.initComponent(this._Item_46_4.context,([] as any[]),compView_46);
    this._text_47 = this.renderer.createText((null as any),'\n            LeftEye RX ',(null as any));
    this._el_48 = this.renderer.createElement((null as any),'ion-note',(null as any));
    this.renderer.setElementAttribute(this._el_48,'item-right','');
    this._Note_48_3 = new import21.Wrapper_Note();
    this._text_49 = this.renderer.createText(this._el_48,'',(null as any));
    this._text_50 = this.renderer.createText((null as any),'\n          ',(null as any));
    this._query_Label_46_0.reset(([] as any[]));
    this._Item_46_4.context.contentLabel = this._query_Label_46_0.first;
    compView_46.create(this._Item_46_4.context,[
      ([] as any[]),
      ([] as any[]),
      ([] as any[]).concat([
        this._text_47,
        this._text_50
      ]
      ),
      ([] as any[]),
      ([] as any[]).concat([this._el_48])
    ]
    ,(null as any));
    this._text_51 = this.renderer.createText(this._el_17,'\n          ',(null as any));
    this._el_52 = this.renderer.createElement(this._el_17,'ion-item',(null as any));
    this.renderer.setElementAttribute(this._el_52,'class','item item-block');
    this._appEl_52 = new import3.AppElement(52,17,this,this._el_52);
    var compView_52:any = import18.viewFactory_Item0(this.viewUtils,this.injector(52),this._appEl_52);
    this._Item_52_4 = new import18.Wrapper_Item(this.parentInjector.get(import31.Form),this.parentInjector.get(import22.Config),new import23.ElementRef(this._el_52),this.renderer,this.parentInjector.get(import32.ItemReorder,(null as any)));
    this._ItemContent_52_5 = new import18.Wrapper_ItemContent();
    this._query_Label_52_0 = new import20.QueryList<any>();
    this._query_Button_52_1 = new import20.QueryList<any>();
    this._query_Icon_52_2 = new import20.QueryList<any>();
    this._appEl_52.initComponent(this._Item_52_4.context,([] as any[]),compView_52);
    this._text_53 = this.renderer.createText((null as any),'\n            RightEye RX ',(null as any));
    this._el_54 = this.renderer.createElement((null as any),'ion-note',(null as any));
    this.renderer.setElementAttribute(this._el_54,'item-right','');
    this._Note_54_3 = new import21.Wrapper_Note();
    this._text_55 = this.renderer.createText(this._el_54,'',(null as any));
    this._text_56 = this.renderer.createText((null as any),'\n          ',(null as any));
    this._query_Label_52_0.reset(([] as any[]));
    this._Item_52_4.context.contentLabel = this._query_Label_52_0.first;
    compView_52.create(this._Item_52_4.context,[
      ([] as any[]),
      ([] as any[]),
      ([] as any[]).concat([
        this._text_53,
        this._text_56
      ]
      ),
      ([] as any[]),
      ([] as any[]).concat([this._el_54])
    ]
    ,(null as any));
    this._text_57 = this.renderer.createText(this._el_17,'\n          ',(null as any));
    this._el_58 = this.renderer.createElement(this._el_17,'ion-item',(null as any));
    this.renderer.setElementAttribute(this._el_58,'class','item item-block');
    this._appEl_58 = new import3.AppElement(58,17,this,this._el_58);
    var compView_58:any = import18.viewFactory_Item0(this.viewUtils,this.injector(58),this._appEl_58);
    this._Item_58_4 = new import18.Wrapper_Item(this.parentInjector.get(import31.Form),this.parentInjector.get(import22.Config),new import23.ElementRef(this._el_58),this.renderer,this.parentInjector.get(import32.ItemReorder,(null as any)));
    this._ItemContent_58_5 = new import18.Wrapper_ItemContent();
    this._query_Label_58_0 = new import20.QueryList<any>();
    this._query_Button_58_1 = new import20.QueryList<any>();
    this._query_Icon_58_2 = new import20.QueryList<any>();
    this._appEl_58.initComponent(this._Item_58_4.context,([] as any[]),compView_58);
    this._text_59 = this.renderer.createText((null as any),'\n            Patient Ref ',(null as any));
    this._el_60 = this.renderer.createElement((null as any),'ion-note',(null as any));
    this.renderer.setElementAttribute(this._el_60,'item-right','');
    this._Note_60_3 = new import21.Wrapper_Note();
    this._text_61 = this.renderer.createText(this._el_60,'',(null as any));
    this._text_62 = this.renderer.createText((null as any),'\n          ',(null as any));
    this._query_Label_58_0.reset(([] as any[]));
    this._Item_58_4.context.contentLabel = this._query_Label_58_0.first;
    compView_58.create(this._Item_58_4.context,[
      ([] as any[]),
      ([] as any[]),
      ([] as any[]).concat([
        this._text_59,
        this._text_62
      ]
      ),
      ([] as any[]),
      ([] as any[]).concat([this._el_60])
    ]
    ,(null as any));
    this._text_63 = this.renderer.createText(this._el_17,'\n        ',(null as any));
    this._text_64 = this.renderer.createText(this._el_15,'\n      ',(null as any));
    this._text_65 = this.renderer.createText(this._el_13,'\n    ',(null as any));
    this._text_66 = this.renderer.createText(this._el_11,'\n  ',(null as any));
    this._text_67 = this.renderer.createText((null as any),'\n',(null as any));
    compView_9.create(this._Content_9_4.context,[
      ([] as any[]),
      ([] as any[]).concat([
        this._text_10,
        this._el_11,
        this._text_67
      ]
      ),
      ([] as any[])
    ]
    ,(null as any));
    this._text_68 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this._expr_1 = import7.UNINITIALIZED;
    this._expr_2 = import7.UNINITIALIZED;
    this._expr_3 = import7.UNINITIALIZED;
    this._expr_4 = import7.UNINITIALIZED;
    this._expr_5 = import7.UNINITIALIZED;
    this._expr_6 = import7.UNINITIALIZED;
    this._expr_7 = import7.UNINITIALIZED;
    this._expr_8 = import7.UNINITIALIZED;
    this._expr_9 = import7.UNINITIALIZED;
    this._expr_10 = import7.UNINITIALIZED;
    this.init(([] as any[]),[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._text_6,
      this._text_7,
      this._text_8,
      this._el_9,
      this._text_10,
      this._el_11,
      this._text_12,
      this._el_13,
      this._text_14,
      this._el_15,
      this._text_16,
      this._el_17,
      this._text_18,
      this._el_19,
      this._text_20,
      this._text_21,
      this._el_22,
      this._text_23,
      this._el_24,
      this._text_25,
      this._text_26,
      this._text_27,
      this._el_28,
      this._text_29,
      this._el_30,
      this._text_31,
      this._text_32,
      this._text_33,
      this._el_34,
      this._text_35,
      this._el_36,
      this._text_37,
      this._text_38,
      this._text_39,
      this._el_40,
      this._text_41,
      this._el_42,
      this._text_43,
      this._text_44,
      this._text_45,
      this._el_46,
      this._text_47,
      this._el_48,
      this._text_49,
      this._text_50,
      this._text_51,
      this._el_52,
      this._text_53,
      this._el_54,
      this._text_55,
      this._text_56,
      this._text_57,
      this._el_58,
      this._text_59,
      this._el_60,
      this._text_61,
      this._text_62,
      this._text_63,
      this._text_64,
      this._text_65,
      this._text_66,
      this._text_67,
      this._text_68
    ]
    ,([] as any[]),([] as any[]));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import33.ToolbarTitle) && ((4 <= requestNodeIndex) && (requestNodeIndex <= 5)))) { return this._ToolbarTitle_4_4.context; }
    if (((token === import34.Navbar) && ((2 <= requestNodeIndex) && (requestNodeIndex <= 6)))) { return this._Navbar_2_4.context; }
    if (((token === import26.Header) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 7)))) { return this._Header_0_3.context; }
    if (((token === import35.Item) && ((19 <= requestNodeIndex) && (requestNodeIndex <= 20)))) { return this._Item_19_4.context; }
    if (((token === import36.ListHeader) && ((19 <= requestNodeIndex) && (requestNodeIndex <= 20)))) { return this._ListHeader_19_5.context; }
    if (((token === import37.Note) && ((24 <= requestNodeIndex) && (requestNodeIndex <= 25)))) { return this._Note_24_3.context; }
    if (((token === import35.Item) && ((22 <= requestNodeIndex) && (requestNodeIndex <= 26)))) { return this._Item_22_4.context; }
    if (((token === import35.ItemContent) && ((22 <= requestNodeIndex) && (requestNodeIndex <= 26)))) { return this._ItemContent_22_5.context; }
    if (((token === import37.Note) && ((30 <= requestNodeIndex) && (requestNodeIndex <= 31)))) { return this._Note_30_3.context; }
    if (((token === import35.Item) && ((28 <= requestNodeIndex) && (requestNodeIndex <= 32)))) { return this._Item_28_4.context; }
    if (((token === import35.ItemContent) && ((28 <= requestNodeIndex) && (requestNodeIndex <= 32)))) { return this._ItemContent_28_5.context; }
    if (((token === import37.Note) && ((36 <= requestNodeIndex) && (requestNodeIndex <= 37)))) { return this._Note_36_3.context; }
    if (((token === import35.Item) && ((34 <= requestNodeIndex) && (requestNodeIndex <= 38)))) { return this._Item_34_4.context; }
    if (((token === import35.ItemContent) && ((34 <= requestNodeIndex) && (requestNodeIndex <= 38)))) { return this._ItemContent_34_5.context; }
    if (((token === import37.Note) && ((42 <= requestNodeIndex) && (requestNodeIndex <= 43)))) { return this._Note_42_3.context; }
    if (((token === import35.Item) && ((40 <= requestNodeIndex) && (requestNodeIndex <= 44)))) { return this._Item_40_4.context; }
    if (((token === import35.ItemContent) && ((40 <= requestNodeIndex) && (requestNodeIndex <= 44)))) { return this._ItemContent_40_5.context; }
    if (((token === import37.Note) && ((48 <= requestNodeIndex) && (requestNodeIndex <= 49)))) { return this._Note_48_3.context; }
    if (((token === import35.Item) && ((46 <= requestNodeIndex) && (requestNodeIndex <= 50)))) { return this._Item_46_4.context; }
    if (((token === import35.ItemContent) && ((46 <= requestNodeIndex) && (requestNodeIndex <= 50)))) { return this._ItemContent_46_5.context; }
    if (((token === import37.Note) && ((54 <= requestNodeIndex) && (requestNodeIndex <= 55)))) { return this._Note_54_3.context; }
    if (((token === import35.Item) && ((52 <= requestNodeIndex) && (requestNodeIndex <= 56)))) { return this._Item_52_4.context; }
    if (((token === import35.ItemContent) && ((52 <= requestNodeIndex) && (requestNodeIndex <= 56)))) { return this._ItemContent_52_5.context; }
    if (((token === import37.Note) && ((60 <= requestNodeIndex) && (requestNodeIndex <= 61)))) { return this._Note_60_3.context; }
    if (((token === import35.Item) && ((58 <= requestNodeIndex) && (requestNodeIndex <= 62)))) { return this._Item_58_4.context; }
    if (((token === import35.ItemContent) && ((58 <= requestNodeIndex) && (requestNodeIndex <= 62)))) { return this._ItemContent_58_5.context; }
    if (((token === import38.List) && ((17 <= requestNodeIndex) && (requestNodeIndex <= 63)))) { return this._List_17_3.context; }
    if (((token === import39.Col) && ((15 <= requestNodeIndex) && (requestNodeIndex <= 64)))) { return this._Col_15_3.context; }
    if (((token === import39.Row) && ((13 <= requestNodeIndex) && (requestNodeIndex <= 65)))) { return this._Row_13_3.context; }
    if (((token === import39.Grid) && ((11 <= requestNodeIndex) && (requestNodeIndex <= 66)))) { return this._Grid_11_3.context; }
    if (((token === import40.Content) && ((9 <= requestNodeIndex) && (requestNodeIndex <= 67)))) { return this._Content_9_4.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._Header_0_3.detectChangesInternal(this,this._el_0,throwOnChange);
    const currVal_0:any = 'lens-dark';
    this._Navbar_2_4.check_color(currVal_0,throwOnChange,false);
    this._Navbar_2_4.detectChangesInternal(this,this._el_2,throwOnChange);
    if (this._ToolbarTitle_4_4.detectChangesInternal(this,this._el_4,throwOnChange)) { this._appEl_4.componentView.markAsCheckOnce(); }
    if (this._Content_9_4.detectChangesInternal(this,this._el_9,throwOnChange)) { this._appEl_9.componentView.markAsCheckOnce(); }
    this._Grid_11_3.detectChangesInternal(this,this._el_11,throwOnChange);
    this._Row_13_3.detectChangesInternal(this,this._el_13,throwOnChange);
    this._Col_15_3.detectChangesInternal(this,this._el_15,throwOnChange);
    this._List_17_3.detectChangesInternal(this,this._el_17,throwOnChange);
    if (this._Item_19_4.detectChangesInternal(this,this._el_19,throwOnChange)) { this._appEl_19.componentView.markAsCheckOnce(); }
    this._ListHeader_19_5.detectChangesInternal(this,this._el_19,throwOnChange);
    if (this._Item_22_4.detectChangesInternal(this,this._el_22,throwOnChange)) { this._appEl_22.componentView.markAsCheckOnce(); }
    this._ItemContent_22_5.detectChangesInternal(this,this._el_22,throwOnChange);
    this._Note_24_3.detectChangesInternal(this,this._el_24,throwOnChange);
    if (this._Item_28_4.detectChangesInternal(this,this._el_28,throwOnChange)) { this._appEl_28.componentView.markAsCheckOnce(); }
    this._ItemContent_28_5.detectChangesInternal(this,this._el_28,throwOnChange);
    this._Note_30_3.detectChangesInternal(this,this._el_30,throwOnChange);
    if (this._Item_34_4.detectChangesInternal(this,this._el_34,throwOnChange)) { this._appEl_34.componentView.markAsCheckOnce(); }
    this._ItemContent_34_5.detectChangesInternal(this,this._el_34,throwOnChange);
    this._Note_36_3.detectChangesInternal(this,this._el_36,throwOnChange);
    if (this._Item_40_4.detectChangesInternal(this,this._el_40,throwOnChange)) { this._appEl_40.componentView.markAsCheckOnce(); }
    this._ItemContent_40_5.detectChangesInternal(this,this._el_40,throwOnChange);
    this._Note_42_3.detectChangesInternal(this,this._el_42,throwOnChange);
    if (this._Item_46_4.detectChangesInternal(this,this._el_46,throwOnChange)) { this._appEl_46.componentView.markAsCheckOnce(); }
    this._ItemContent_46_5.detectChangesInternal(this,this._el_46,throwOnChange);
    this._Note_48_3.detectChangesInternal(this,this._el_48,throwOnChange);
    if (this._Item_52_4.detectChangesInternal(this,this._el_52,throwOnChange)) { this._appEl_52.componentView.markAsCheckOnce(); }
    this._ItemContent_52_5.detectChangesInternal(this,this._el_52,throwOnChange);
    this._Note_54_3.detectChangesInternal(this,this._el_54,throwOnChange);
    if (this._Item_58_4.detectChangesInternal(this,this._el_58,throwOnChange)) { this._appEl_58.componentView.markAsCheckOnce(); }
    this._ItemContent_58_5.detectChangesInternal(this,this._el_58,throwOnChange);
    this._Note_60_3.detectChangesInternal(this,this._el_60,throwOnChange);
    this.detectContentChildrenChanges(throwOnChange);
    if (!throwOnChange) {
      if (this._query_Button_19_1.dirty) {
        this._query_Button_19_1.reset(([] as any[]));
        this._Item_19_4.context._buttons = this._query_Button_19_1;
        this._query_Button_19_1.notifyOnChanges();
      }
      if (this._query_Icon_19_2.dirty) {
        this._query_Icon_19_2.reset(([] as any[]));
        this._Item_19_4.context._icons = this._query_Icon_19_2;
        this._query_Icon_19_2.notifyOnChanges();
      }
      if (this._query_Button_22_1.dirty) {
        this._query_Button_22_1.reset(([] as any[]));
        this._Item_22_4.context._buttons = this._query_Button_22_1;
        this._query_Button_22_1.notifyOnChanges();
      }
      if (this._query_Icon_22_2.dirty) {
        this._query_Icon_22_2.reset(([] as any[]));
        this._Item_22_4.context._icons = this._query_Icon_22_2;
        this._query_Icon_22_2.notifyOnChanges();
      }
      if (this._query_Button_28_1.dirty) {
        this._query_Button_28_1.reset(([] as any[]));
        this._Item_28_4.context._buttons = this._query_Button_28_1;
        this._query_Button_28_1.notifyOnChanges();
      }
      if (this._query_Icon_28_2.dirty) {
        this._query_Icon_28_2.reset(([] as any[]));
        this._Item_28_4.context._icons = this._query_Icon_28_2;
        this._query_Icon_28_2.notifyOnChanges();
      }
      if (this._query_Button_34_1.dirty) {
        this._query_Button_34_1.reset(([] as any[]));
        this._Item_34_4.context._buttons = this._query_Button_34_1;
        this._query_Button_34_1.notifyOnChanges();
      }
      if (this._query_Icon_34_2.dirty) {
        this._query_Icon_34_2.reset(([] as any[]));
        this._Item_34_4.context._icons = this._query_Icon_34_2;
        this._query_Icon_34_2.notifyOnChanges();
      }
      if (this._query_Button_40_1.dirty) {
        this._query_Button_40_1.reset(([] as any[]));
        this._Item_40_4.context._buttons = this._query_Button_40_1;
        this._query_Button_40_1.notifyOnChanges();
      }
      if (this._query_Icon_40_2.dirty) {
        this._query_Icon_40_2.reset(([] as any[]));
        this._Item_40_4.context._icons = this._query_Icon_40_2;
        this._query_Icon_40_2.notifyOnChanges();
      }
      if (this._query_Button_46_1.dirty) {
        this._query_Button_46_1.reset(([] as any[]));
        this._Item_46_4.context._buttons = this._query_Button_46_1;
        this._query_Button_46_1.notifyOnChanges();
      }
      if (this._query_Icon_46_2.dirty) {
        this._query_Icon_46_2.reset(([] as any[]));
        this._Item_46_4.context._icons = this._query_Icon_46_2;
        this._query_Icon_46_2.notifyOnChanges();
      }
      if (this._query_Button_52_1.dirty) {
        this._query_Button_52_1.reset(([] as any[]));
        this._Item_52_4.context._buttons = this._query_Button_52_1;
        this._query_Button_52_1.notifyOnChanges();
      }
      if (this._query_Icon_52_2.dirty) {
        this._query_Icon_52_2.reset(([] as any[]));
        this._Item_52_4.context._icons = this._query_Icon_52_2;
        this._query_Icon_52_2.notifyOnChanges();
      }
      if (this._query_Button_58_1.dirty) {
        this._query_Button_58_1.reset(([] as any[]));
        this._Item_58_4.context._buttons = this._query_Button_58_1;
        this._query_Button_58_1.notifyOnChanges();
      }
      if (this._query_Icon_58_2.dirty) {
        this._query_Icon_58_2.reset(([] as any[]));
        this._Item_58_4.context._icons = this._query_Icon_58_2;
        this._query_Icon_58_2.notifyOnChanges();
      }
      if ((this.numberOfChecks === 0)) { this._Item_19_4.context.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Item_22_4.context.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Item_28_4.context.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Item_34_4.context.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Item_40_4.context.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Item_46_4.context.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Item_52_4.context.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Item_58_4.context.ngAfterContentInit(); }
    }
    const currVal_1:any = this._Navbar_2_4.context._hidden;
    if (import4.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this.renderer.setElementProperty(this._el_2,'hidden',currVal_1);
      this._expr_1 = currVal_1;
    }
    const currVal_2:any = this._Navbar_2_4.context._sbPadding;
    if (import4.checkBinding(throwOnChange,this._expr_2,currVal_2)) {
      this.renderer.setElementClass(this._el_2,'statusbar-padding',currVal_2);
      this._expr_2 = currVal_2;
    }
    const currVal_3:any = this._Content_9_4.context._sbPadding;
    if (import4.checkBinding(throwOnChange,this._expr_3,currVal_3)) {
      this.renderer.setElementClass(this._el_9,'statusbar-padding',currVal_3);
      this._expr_3 = currVal_3;
    }
    const currVal_4:any = import4.interpolate(1,' ',this.context.lens.lensChoosen.name,' ');
    if (import4.checkBinding(throwOnChange,this._expr_4,currVal_4)) {
      this.renderer.setText(this._text_25,currVal_4);
      this._expr_4 = currVal_4;
    }
    const currVal_5:any = import4.interpolate(1,' ',this.context.lens.lensType,' ');
    if (import4.checkBinding(throwOnChange,this._expr_5,currVal_5)) {
      this.renderer.setText(this._text_31,currVal_5);
      this._expr_5 = currVal_5;
    }
    const currVal_6:any = import4.interpolate(1,' ',this.context.lens.lensModality,' ');
    if (import4.checkBinding(throwOnChange,this._expr_6,currVal_6)) {
      this.renderer.setText(this._text_37,currVal_6);
      this._expr_6 = currVal_6;
    }
    const currVal_7:any = import4.interpolate(1,' ',this.context.lens.RX.wasAdjusted,' ');
    if (import4.checkBinding(throwOnChange,this._expr_7,currVal_7)) {
      this.renderer.setText(this._text_43,currVal_7);
      this._expr_7 = currVal_7;
    }
    const currVal_8:any = import4.interpolate(1,' ',this.context.lens.RX.l,' ');
    if (import4.checkBinding(throwOnChange,this._expr_8,currVal_8)) {
      this.renderer.setText(this._text_49,currVal_8);
      this._expr_8 = currVal_8;
    }
    const currVal_9:any = import4.interpolate(1,' ',this.context.lens.RX.r,' ');
    if (import4.checkBinding(throwOnChange,this._expr_9,currVal_9)) {
      this.renderer.setText(this._text_55,currVal_9);
      this._expr_9 = currVal_9;
    }
    const currVal_10:any = import4.interpolate(1,' ',this.context.lens.patientRef,' ');
    if (import4.checkBinding(throwOnChange,this._expr_10,currVal_10)) {
      this.renderer.setText(this._text_61,currVal_10);
      this._expr_10 = currVal_10;
    }
    this.detectViewChildrenChanges(throwOnChange);
    if (!throwOnChange) { if ((this.numberOfChecks === 0)) { this._Navbar_2_4.context.ngAfterViewInit(); } }
  }
  destroyInternal():void {
    this._Content_9_4.context.ngOnDestroy();
  }
}
export function viewFactory_OrderDetailsPage0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement):import1.AppView<import0.OrderDetailsPage> {
  if ((renderType_OrderDetailsPage === (null as any))) { (renderType_OrderDetailsPage = viewUtils.createRenderComponentType('',0,import10.ViewEncapsulation.None,styles_OrderDetailsPage,{})); }
  return new _View_OrderDetailsPage0(viewUtils,parentInjector,declarationEl);
}